import 'package:get_topik_korean_quiz/models/quiz.module.dart';

List<QuizTest> book1QuizData = [
  // #2.1 Unit
  QuizTest(
    id: 1,
    unitNumber: 2.1,
    question: '안녕하세요',
    options: ['Xayr', 'Yaxshi qoling', 'Assalomu alaykum', 'Yaxshi boring'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 2,
    unitNumber: 2.1,
    question: '만나서 반갑습니다',
    options: [
      'Kechirasiz',
      'Tanishganimdan xursandman',
      'Hammasi joyida',
      'Raxmat'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 3,
    unitNumber: 2.1,
    question: '안녕히 가세요',
    options: ['Yaxshi qoling', 'Uzr', 'Yaxshi', 'Yaxshi boring'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 4,
    unitNumber: 2.1,
    question: '안녕히 계세요',
    options: ['Yaxshi boring', 'Yaxshi qoling', 'Yaxshi', 'Uzr'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 5,
    unitNumber: 2.1,
    question: '미안합니다',
    options: ['Raxmat', 'Hammasi joyida', 'Uzr', 'Yaxshi'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 6,
    unitNumber: 2.1,
    question: '괜찮습니다',
    options: ['Yaxshi', 'Hammasi joyida', 'Raxmat', 'Uzr'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 7,
    unitNumber: 2.1,
    question: '고맙습니다',
    options: ['Uzr', 'Yaxshi', 'Hammasi joyida', 'Raxmat'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 8,
    unitNumber: 2.1,
    question: '동사',
    options: ['ot', 'sifat', 'fe\'l', 'ravish'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 9,
    unitNumber: 2.1,
    question: '가다',
    options: ['kelmoq', 'chiqmoq', 'bormoq', 'o\'qimoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 10,
    unitNumber: 2.1,
    question: '오다',
    options: ['kulmoq', 'kelmoq', 'bormoq', 'ketmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 11,
    unitNumber: 2.1,
    question: '자다',
    options: ['uxlamoq', 'suhbatlashmoq', 'o\'qimoq', 'gapirmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 2.1,
    question: '보다',
    options: ['o\'qimoq', 'boshlamoq', 'ko\'rmoq', 'aytmoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 13,
    unitNumber: 2.1,
    question: '먹다',
    options: ['boshlamoq', 'o\'qimoq', 'gapirmoq', 'yemoq'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 14,
    unitNumber: 2.1,
    question: '읽다',
    options: ['ko\'rmoq', 'o\'qimoq', 'aytmoq', 'yig\'lamoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 15,
    unitNumber: 2.1,
    question: '공부하다',
    options: ['sotib olmoq', 'ta\'lim olmoq', 'uchrashmoq', 'sotmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 16,
    unitNumber: 2.1,
    question: '형용사 ',
    options: ['fe\'l', 'sifat', 'ravish', 'ot'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 17,
    unitNumber: 2.1,
    question: '좋다',
    options: ['katta', 'kichik', 'yaxshi', 'kam'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 18,
    unitNumber: 2.1,
    question: '크다',
    options: ['kam', 'katta', 'ko\'p', 'kichik'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 2.1,
    question: '작다',
    options: ['yaxshi', 'katta', 'kam', 'kichik'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 20,
    unitNumber: 2.1,
    question: '많다',
    options: ['kam', 'katta', 'ko\'p', 'kichik'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 21,
    unitNumber: 2.1,
    question: '적다',
    options: ['yaxshi', 'katta', 'kam', 'kichik'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 22,
    unitNumber: 2.1,
    question: '재미있다',
    options: ['qiziqarli', 'yaxshi', 'qiziqarsiz', 'ko\'p'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 2.1,
    question: '재미없다',
    options: ['yaxshi emas', 'qiziqarli', 'zerikarli', 'kam'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 24,
    unitNumber: 2.1,
    question: '학생',
    options: ['hayot', 'o\'quvchi', 'o\'qituvchi', 'koreys tili'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 25,
    unitNumber: 2.1,
    question: '친구',
    options: ['kitob', 'do\'st', 'kiyim', 'hayot'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 26,
    unitNumber: 2.1,
    question: '선생님',
    options: ['koreys tili', 'o\'qituvchi', 'o\'quvchi', 'kitob'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 27,
    unitNumber: 2.1,
    question: '한국어',
    options: ['koreys tili', 'Koreya', 'koreya hayoti', 'Koreya odami'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 2.1,
    question: '운동하다',
    options: [
      'ta\'lim olmoq',
      'dars qilmoq',
      'sport bilan shug\'illanmoq',
      'ketmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 29,
    unitNumber: 2.1,
    question: '옷',
    options: ['kulmoq', 'kiyim', 'kitob', 'soyabon'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 30,
    unitNumber: 2.1,
    question: '책',
    options: ['parta', 'stul', 'kiyim', 'kitob'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 31,
    unitNumber: 2.1,
    question: '의자',
    options: ['doska', 'stul', 'parta', 'stol'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 32,
    unitNumber: 2.1,
    question: '책상',
    options: ['stul', 'parta', 'doska', 'kitob'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 33,
    unitNumber: 2.1,
    question: '한국',
    options: ['koreyalik ', 'koreys tili', 'Koreya', 'koreya hayoti'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 34,
    unitNumber: 2.1,
    question: '생활',
    options: ['hayot', 'parta', 'o\'qituvchi', 'koreyalik'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 35,
    unitNumber: 2.1,
    question: '어떻다',
    options: ['qayer', 'qanaqa', 'qaysi', 'qancha'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 36,
    unitNumber: 2.1,
    question: '아주',
    options: ['tez-tez', 'ko\'p', 'hozir', 'juda'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 37,
    unitNumber: 2.1,
    question: '대학교',
    options: ['maktab', 'universitet', 'o\'quv markazi', 'park'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 38,
    unitNumber: 2.1,
    question: '이름',
    options: ['yosh', 'raqam', 'ism', 'sinf'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 39,
    unitNumber: 2.1,
    question: '전화번호',
    options: [
      'telefon',
      'telefon qilmoq',
      'telefonda gaplashmoq',
      'telefon raqam'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 40,
    unitNumber: 2.1,
    question: '공부',
    options: ['ta\'lim olish', 'ta\'lim olmoq', 'mashq qilmoq', 'kitob'],
    correctOptionIndex: 0,
  ),

// #2.2 Unit
  QuizTest(
    id: 41,
    unitNumber: 2.2,
    question: '나라',
    options: ['yosh', 'davlat', 'chet ellik', 'odam'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 42,
    unitNumber: 2.2,
    question: '사람',
    options: ['chet el', 'yosh', 'odam', 'davlat'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 43,
    unitNumber: 2.2,
    question: '한국',
    options: ['Xitoy', 'Koreya', 'Angliya', 'Yevropa'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 44,
    unitNumber: 2.2,
    question: '한국 사람',
    options: ['Koreya', 'koreya hayoti', 'koreyalik', 'koreys tili'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 45,
    unitNumber: 2.2,
    question: '중국',
    options: ['Xitoy', 'Yaponiya', 'Vetnam', 'Koreya'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 46,
    unitNumber: 2.2,
    question: '중국 사람',
    options: ['vetnamlik', 'koreyalik', 'xitoylik', 'amerikalik'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 47,
    unitNumber: 2.2,
    question: '일본',
    options: ['Vetnam', 'Yaponiya', 'Koreya', 'Amerika'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 48,
    unitNumber: 2.2,
    question: '일본 사람',
    options: ['yaponiyalik', 'koreyalik', 'vetnamlik', 'xitoylik'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 49,
    unitNumber: 2.2,
    question: '몽굴',
    options: ['Yaponiya', 'Koreya', 'Amerika', 'Mongoliya'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 50,
    unitNumber: 2.2,
    question: '몽굴 사람',
    options: ['amerikalik', 'mongoliyalik', 'yaponiyalik', 'koreyalik'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 51,
    unitNumber: 2.2,
    question: '러시아',
    options: ['Xitoy', 'Vetnam', 'Rossiya', 'Amerika'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 52,
    unitNumber: 2.2,
    question: '러시아 사람',
    options: ['vetnamlik', 'rossiyalik', 'angliyalik', 'amerikalik'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 53,
    unitNumber: 2.2,
    question: '베트남',
    options: ['Xitoy', 'Vetnam', 'Rossiya', 'Amerika'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 54,
    unitNumber: 2.2,
    question: '베트남 사람',
    options: ['vetnamlik', 'rossiyalik', 'angliyalik', 'amerikalik'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 55,
    unitNumber: 2.2,
    question: '영국',
    options: ['Xitoy', 'Angliya', 'Rossiya', 'Amerika'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 56,
    unitNumber: 2.2,
    question: '영국 사람',
    options: ['vetnamlik', 'rossiyalik', 'angliyalik', 'amerikalik'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 57,
    unitNumber: 2.2,
    question: '독일',
    options: ['Angliya', 'Germaniya', 'Rossiya', 'Amerika'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 58,
    unitNumber: 2.2,
    question: '독일 사람',
    options: ['rossiyalik', 'angliyalik', 'germaniyalik', 'amerikalik'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 59,
    unitNumber: 2.2,
    question: '미국',
    options: ['Xitoy', 'Vetnam', 'Rossiya', 'Amerika'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 60,
    unitNumber: 2.2,
    question: '미국 사람',
    options: ['angliyalik', 'rossiyalik', 'angliyalik', 'amerikalik'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 61,
    unitNumber: 2.2,
    question: '저',
    options: ['sen', 'men', 'u', 'biz'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 62,
    unitNumber: 2.2,
    question: '회사원',
    options: ['oshpaz', 'shifokor', 'firma xodimi', 'kasb'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 63,
    unitNumber: 2.2,
    question: '무엇',
    options: ['kim', 'qaysi', 'qayer', 'nima'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 64,
    unitNumber: 2.2,
    question: '제(저의)',
    options: ['men', 'mening', 'biz', 'u'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 65,
    unitNumber: 2.2,
    question: '고향',
    options: ['vatan', 'park', 'davlat', 'kasb'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 66,
    unitNumber: 2.2,
    question: '여자',
    options: ['erkak', 'ayol', 'firma xodimi', 'kim'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 67,
    unitNumber: 2.2,
    question: '의사',
    options: ['firma xodimi', 'hamshira', 'aktyor', 'shifokor'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 68,
    unitNumber: 2.2,
    question: '우리',
    options: ['siz', 'biz', 'u', 'ular'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 69,
    unitNumber: 2.2,
    question: '남자',
    options: ['hamshira', 'ayol', 'erkak', 'shifokor'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 70,
    unitNumber: 2.2,
    question: '직업',
    options: ['hamyon', 'ta\'lim', 'ish', 'kasb'],
    correctOptionIndex: 3,
  ),

  // #2.3 Unit

  QuizTest(
    id: 71,
    unitNumber: 2.3,
    question: '가족',
    options: ['opa', 'uka', 'oila', 'aka'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 72,
    unitNumber: 2.3,
    question: '할아버지',
    options: ['ota', 'bobo', 'buvi', 'ona'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 73,
    unitNumber: 2.3,
    question: '할머니',
    options: ['ota', 'buvi', 'bobo', 'ona'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 74,
    unitNumber: 2.3,
    question: '외할아버지',
    options: ['ota', 'buvi (ona tomon)', 'bobo (ona tomon)', 'ona'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 75,
    unitNumber: 2.3,
    question: '외할머니',
    options: ['bobo (ona tomon)', 'ota', 'buvi (ona tomon)', 'ona'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 76,
    unitNumber: 2.3,
    question: '아버지',
    options: ['bobo', 'ota', 'ona', 'buvi'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 77,
    unitNumber: 2.3,
    question: '어머니',
    options: ['bobo', 'ota', 'ona', 'buvi'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 78,
    unitNumber: 2.3,
    question: '오빠 / 형',
    options: ['uka', 'opa', 'singil', 'aka'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 79,
    unitNumber: 2.3,
    question: '언니 / 누나',
    options: ['opa', 'uka', 'aka', 'singil'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 80,
    unitNumber: 2.3,
    question: '나',
    options: ['biz', 'men', 'sen', 'u'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 11,
    unitNumber: 2.3,
    question: '의사',
    options: ['stul', 'shifokor', 'hamshira', 'parta'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 2.3,
    question: '남동생',
    options: ['aka', 'uka', 'singil', 'opa'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 2.3,
    question: '여동생',
    options: ['aka', 'uka', 'singil', 'opa'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 14,
    unitNumber: 2.3,
    question: '직업',
    options: ['ta\'lim', 'kasb', 'oila', 'farzand'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 15,
    unitNumber: 2.3,
    question: '회사원',
    options: ['shifokor', 'savdogar', 'firma xodimi', 'oshpaz'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 16,
    unitNumber: 2.3,
    question: '가수',
    options: ['qo\'shiqchi', 'aktyor', 'hamshira', 'rassom'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 2.3,
    question: '간호사',
    options: ['rassom', 'hamshira', 'shifokor', 'aktyor'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 18,
    unitNumber: 2.3,
    question: '은행원',
    options: ['bank xodimi', 'tadbirkor', 'shifokor', 'aktyor'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 2.3,
    question: '주부',
    options: ['aktrisa', 'uy bekasi', 'qo\'shiqchi', 'hamshira'],
    correctOptionIndex: 1,
  ),

  QuizTest(
    id: 20,
    unitNumber: 2.3,
    question: '사업가',
    options: ['biznesmen', 'oshpaz', 'haydovchi', 'shifokor'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 2.3,
    question: '경찰관',
    options: ['sartarosh', 'politsiya xodimi', 'mutaxassislik', 'oshpaz'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 22,
    unitNumber: 2.3,
    question: '미용사',
    options: ['sartarosh', 'politsiya xodimi', 'mutaxassislik', 'oshpaz'],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 23,
    unitNumber: 2.3,
    question: '요리사',
    options: ['sartarosh', 'politsiya xodimi', 'mutaxassislik', 'oshpaz'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 24,
    unitNumber: 2.3,
    question: '누구',
    options: ['nima', 'kim', 'qachon', 'qayer'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 25,
    unitNumber: 2.3,
    question: '전공',
    options: ['serial', 'mutaxassislik', 'kasb', 'kishi'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 26,
    unitNumber: 2.3,
    question: '이',
    options: ['biz', 'men', 'sen', 'bu / 2 / tish'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 27,
    unitNumber: 2.3,
    question: '유학생',
    options: ['o\'qituvchi', 'chet ellik talaba', 'o\'quvchi', 'talaba'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 28,
    unitNumber: 2.3,
    question: '좋아하다',
    options: ['yaxshi', 'katta', 'yoqtirmoq', 'serial'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 29,
    unitNumber: 2.3,
    question: '드라마',
    options: ['serial', 'gazeta', 'kino', 'kim'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 2.3,
    question: '신문',
    options: ['kitob', 'gazeta', 'serial', 'kino'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 31,
    unitNumber: 2.3,
    question: '주무시다',
    options: ['yemoq', 'yoqtirmoq', 'uxlamoq', 'suhbatlashmoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 32,
    unitNumber: 2.3,
    question: '점심',
    options: ['kechki ovqat', 'tushlik', 'nonushta', 'ovqat'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 33,
    unitNumber: 2.3,
    question: '마시다',
    options: ['ichmoq', 'yemoq', 'tayyorlamoq', 'gapirmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 2.3,
    question: '말씀하시다',
    options: ['suhbatlasmoq', 'gapirmoq', 'kulmoq', 'uxlamoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 35,
    unitNumber: 2.3,
    question: '요리하다',
    options: ['yemoq', 'ovqat tayyorlamoq', 'yoqtirmoq', 'gapirmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 36,
    unitNumber: 2.3,
    question: '이야기하다',
    options: ['uxlamoq', 'yemoq', 'suhbatlashmoq', 'kuylamoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 37,
    unitNumber: 2.3,
    question: '공무원',
    options: ['davlat', 'davlat ishchisi', 'bank', 'bank xodimi'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 38,
    unitNumber: 2.3,
    question: '명',
    options: ['nima', 'kishi', 'va', 'ammo'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 39,
    unitNumber: 2.3,
    question: '한',
    options: ['3', '4', '1', '2'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 40,
    unitNumber: 2.3,
    question: '두',
    options: ['1', '4', '2', '3'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 41,
    unitNumber: 2.3,
    question: '세',
    options: ['1', '4', '2', '3'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 42,
    unitNumber: 2.3,
    question: '네',
    options: ['1', '4', '2', '3'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 43,
    unitNumber: 2.3,
    question: '다섯',
    options: ['6', '5', '7', '4'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 44,
    unitNumber: 2.3,
    question: '여섯',
    options: ['10', '6', '3', '5'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 45,
    unitNumber: 2.3,
    question: '그리고',
    options: ['ammo', 'va', 'shuning uchun', 'u'],
    correctOptionIndex: 1,
  ),

  // #3.1 Unit
  QuizTest(
    id: 1,
    unitNumber: 3.1,
    question: '영화',
    options: ['teatr', 'kino', 'kitob', 'musiqa'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 2,
    unitNumber: 3.1,
    question: '십구',
    options: ['18', '19', '20', '21'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 3,
    unitNumber: 3.1,
    question: '시',
    options: ['soat', 'daqiqalar', 'vaqt', 'kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 3.1,
    question: '여섯',
    options: ['6', '7', '8', '9'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 3.1,
    question: '넷(네)',
    options: ['1', '2', '3', '4'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 6,
    unitNumber: 3.1,
    question: '육십',
    options: ['50', '60', '70', '80'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 7,
    unitNumber: 3.1,
    question: '아침',
    options: ['nonushta', 'tushlik(obet)', 'kechlik(ujin)', 'tun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 3.1,
    question: '십',
    options: ['9', '10', '11', '12'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 9,
    unitNumber: 3.1,
    question: '이',
    options: ['1', '2', '3', '4'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 10,
    unitNumber: 3.1,
    question: '몇',
    options: ['qachon?', 'necha?', 'qancha?', 'kim?'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 11,
    unitNumber: 3.1,
    question: '칠',
    options: ['6', '7', '8', '9'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 3.1,
    question: '오전',
    options: [
      'PM/kun ikkinchi yarim',
      'AM/kun birinchi yarim',
      'ertalab',
      'kechqurun'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 3.1,
    question: '열셋(열세)',
    options: ['12', '13', '14', '15'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 14,
    unitNumber: 3.1,
    question: '구십',
    options: ['80', '90', '100', '110'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 15,
    unitNumber: 3.1,
    question: '일',
    options: ['1', '2', '3', '4'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 3.1,
    question: '오십',
    options: ['40', '50', '60', '70'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 17,
    unitNumber: 3.1,
    question: '백',
    options: ['90', '100', '110', '120'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 18,
    unitNumber: 3.1,
    question: '십일',
    options: ['10', '11', '12', '13'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 3.1,
    question: '넷',
    options: ['3', '4', '5', '6'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 20,
    unitNumber: 3.1,
    question: '샤워를 하다',
    options: ['dush qabul qilmoq', 'tish yuvmoq', 'qo\'l yuvmoq', 'uxlamoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 3.1,
    question: '점심',
    options: ['tun', 'kun', 'ertalab', 'tush(obet)'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 22,
    unitNumber: 3.1,
    question: '여덟',
    options: ['7', '8', '9', '10'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 23,
    unitNumber: 3.1,
    question: '끝나다',
    options: ['boshlamoq', 'tugamoq', 'uxlamoq', 'ichmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 24,
    unitNumber: 3.1,
    question: '이십이',
    options: ['21', '22', '23', '24'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 25,
    unitNumber: 3.1,
    question: '십칠',
    options: ['16', '17', '18', '19'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 26,
    unitNumber: 3.1,
    question: '밥',
    options: ['guruch(ovqat)', 'qahva', 'non', 'sho\'rva'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 3.1,
    question: '수',
    options: ['raqam', 'xitoy raqam', 'soat', 'vaqt'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 3.1,
    question: '십사',
    options: ['13', '14', '15', '16'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 29,
    unitNumber: 3.1,
    question: '언제?',
    options: ['qachon?', 'necha?', 'qancha?', 'kim?'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 3.1,
    question: '열',
    options: ['9', '10', '11', '12'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 31,
    unitNumber: 3.1,
    question: '십이',
    options: ['11', '12', '13', '14'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 32,
    unitNumber: 3.1,
    question: '십육',
    options: ['15', '16', '17', '18'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 33,
    unitNumber: 3.1,
    question: '육',
    options: ['5', '6', '7', '8'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 34,
    unitNumber: 3.1,
    question: '십삼',
    options: ['12', '13', '14', '15'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 35,
    unitNumber: 3.1,
    question: '열하나(열한)',
    options: ['10', '11', '12', '13'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 36,
    unitNumber: 3.1,
    question: '십팔',
    options: ['17', '18', '19', '20'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 37,
    unitNumber: 3.1,
    question: '스물(스무)',
    options: ['19', '20', '21', '22'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 38,
    unitNumber: 3.1,
    question: '아홉',
    options: ['8', '9', '10', '11'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 39,
    unitNumber: 3.1,
    question: '사',
    options: ['3', '4', '5', '6'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 40,
    unitNumber: 3.1,
    question: '열일곱',
    options: ['16', '17', '18', '19'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 41,
    unitNumber: 3.1,
    question: '마시다',
    options: ['ichmoq', 'yemoq', 'uxlamoq', 'eshitmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 42,
    unitNumber: 3.1,
    question: '사과',
    options: ['olma', 'uzum', 'apelsin', 'banan'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 43,
    unitNumber: 3.1,
    question: '열넷',
    options: ['13', '14', '15', '16'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 44,
    unitNumber: 3.1,
    question: '한국 숫자',
    options: ['xitoy raqam', 'koreys raqam', 'raqam', 'soat'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 45,
    unitNumber: 3.1,
    question: '커피',
    options: ['choy', 'suv', 'qahva', 'sharbat'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 46,
    unitNumber: 3.1,
    question: '열다섯',
    options: ['14', '15', '16', '17'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 47,
    unitNumber: 3.1,
    question: '오',
    options: ['4', '5', '6', '7'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 48,
    unitNumber: 3.1,
    question: '열둘(열두)',
    options: ['11', '12', '13', '14'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 49,
    unitNumber: 3.1,
    question: '음악',
    options: ['kino', 'teatr', 'musiqa', 'kitob'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 50,
    unitNumber: 3.1,
    question: '이십',
    options: ['19', '20', '21', '22'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 51,
    unitNumber: 3.1,
    question: '여덟',
    options: ['7', '8', '9', '10'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 52,
    unitNumber: 3.1,
    question: '수업',
    options: ['dars', 'kitob', 'sinov', 'imlo'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 53,
    unitNumber: 3.1,
    question: '아흔',
    options: ['80', '90', '100', '110'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 54,
    unitNumber: 3.1,
    question: '일곱',
    options: ['6', '7', '8', '9'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 55,
    unitNumber: 3.1,
    question: '서른',
    options: ['20', '30', '40', '50'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 56,
    unitNumber: 3.1,
    question: '일아나다',
    options: ['uxlamoq', 'uyqudan turmoq', 'yotmoq', 'turmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 57,
    unitNumber: 3.1,
    question: '쉰',
    options: ['40', '50', '60', '70'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 58,
    unitNumber: 3.1,
    question: '사십',
    options: ['30', '40', '50', '60'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 59,
    unitNumber: 3.1,
    question: '수물하나',
    options: ['20', '21', '22', '23'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 60,
    unitNumber: 3.1,
    question: '저녁',
    options: ['kechlik(ujin)', 'tun', 'kunduzi', 'ertalab'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 61,
    unitNumber: 3.1,
    question: '낮',
    options: ['tun', 'kunduzi', 'ertalab', 'tush(obet)'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 62,
    unitNumber: 3.1,
    question: '열일곱',
    options: ['16', '17', '18', '19'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 63,
    unitNumber: 3.1,
    question: '점심',
    options: ['tun', 'kun', 'ertalab', 'tush(obet)'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 64,
    unitNumber: 3.1,
    question: '밤',
    options: ['tun', 'kun', 'ertalab', 'tush(obet)'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 65,
    unitNumber: 3.1,
    question: '오후',
    options: [
      'AM/kun birinchi yarimi',
      'PM/kun ikkinchi yarimi',
      'ertalab',
      'kechqurun'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 66,
    unitNumber: 3.1,
    question: '둘(두)',
    options: ['1', '2', '3', '4'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 67,
    unitNumber: 3.1,
    question: '칠십',
    options: ['60', '70', '80', '90'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 68,
    unitNumber: 3.1,
    question: '칠십',
    options: ['60', '70', '80', '90'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 69,
    unitNumber: 3.1,
    question: '삼',
    options: ['2', '3', '4', '5'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 70,
    unitNumber: 3.1,
    question: '열넷',
    options: ['13', '14', '15', '16'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 71,
    unitNumber: 3.1,
    question: '이십일',
    options: ['20', '21', '22', '23'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 72,
    unitNumber: 3.1,
    question: '셋(세)',
    options: ['1', '2', '3', '4'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 73,
    unitNumber: 3.1,
    question: '점심',
    options: ['tun', 'kun', 'ertalab', 'tush(obet)'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 74,
    unitNumber: 3.1,
    question: '스물둘',
    options: ['21', '22', '23', '24'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 75,
    unitNumber: 3.1,
    question: '여섯',
    options: ['6', '7', '8', '9'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 76,
    unitNumber: 3.1,
    question: '예순',
    options: ['50', '60', '70', '80'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 77,
    unitNumber: 3.1,
    question: '사',
    options: ['3', '4', '5', '6'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 78,
    unitNumber: 3.1,
    question: '텔레비전',
    options: ['telefon', 'kompyuter', 'televizor', 'radio'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 79,
    unitNumber: 3.1,
    question: '영화',
    options: ['kitob', 'kino', 'musqa', 'teatr'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 80,
    unitNumber: 3.1,
    question: '팔',
    options: ['7', '8', '9', '10'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 81,
    unitNumber: 3.1,
    question: '쯤',
    options: ['-larcha, atrofida', '-gacha', '-dan oldin', '-dan keyin'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 82,
    unitNumber: 3.1,
    question: '팔십',
    options: ['70', '80', '90', '100'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 83,
    unitNumber: 3.1,
    question: '보통',
    options: ['odatda', 'tez-tez', 'kamdan-kam', 'umuman'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 84,
    unitNumber: 3.1,
    question: '그럼',
    options: [
      'unda, u holda, unday bo\'lsa',
      'lekin',
      'ammo',
      'shunday bo\'lsa ham'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 85,
    unitNumber: 3.1,
    question: '사십',
    options: ['30', '40', '50', '60'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 86,
    unitNumber: 3.1,
    question: '끝나다',
    options: ['boshlamoq', 'tugamoq', 'uxlamoq', 'ichmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 87,
    unitNumber: 3.1,
    question: '잠을 자다',
    options: ['uyqudan turmoq', 'uxlamoq', 'kitob o\'qimoq', 'dars qilmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 88,
    unitNumber: 3.1,
    question: '육십',
    options: ['50', '60', '70', '80'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 89,
    unitNumber: 3.1,
    question: '넷',
    options: ['3', '4', '5', '6'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 90,
    unitNumber: 3.1,
    question: '칠십',
    options: ['60', '70', '80', '90'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 91,
    unitNumber: 3.1,
    question: '팔십',
    options: ['70', '80', '90', '100'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 92,
    unitNumber: 3.1,
    question: '칠',
    options: ['6', '7', '8', '9'],
    correctOptionIndex: 1,
  ),

  // #3.2 Unit
  QuizTest(
    id: 1,
    unitNumber: 3.2,
    question: '날짜',
    options: ['oy', 'kun', 'yomg`ir', 'sana'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 2,
    unitNumber: 3.2,
    question: '몇',
    options: ['nechanchi', 'oy', 'yanvar', 'kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 3.2,
    question: '월',
    options: ['nechanchi', 'tug`ilgan kun', 'oy', 'kun'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 4,
    unitNumber: 3.2,
    question: '일월',
    options: ['yanvar', 'aprel', 'fevral', 'may'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 3.2,
    question: '이월',
    options: ['yanvar', 'aprel', 'fevral', 'mart'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 6,
    unitNumber: 3.2,
    question: '삼월',
    options: ['aprel', 'mart', 'iyun', 'avgust'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 7,
    unitNumber: 3.2,
    question: '사월',
    options: ['oktabr', 'iyul', 'aprel', 'may'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 8,
    unitNumber: 3.2,
    question: '오월',
    options: ['iyul', 'mart', 'may', 'aprel'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 9,
    unitNumber: 3.2,
    question: '유월',
    options: ['iyul', 'iyun', 'avgust', 'may'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 10,
    unitNumber: 3.2,
    question: '칠월',
    options: ['sentabr', 'iyun', 'iyul', 'may'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 11,
    unitNumber: 3.2,
    question: '팔월',
    options: ['noyabr', 'iyun', 'avgust', 'may'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 12,
    unitNumber: 3.2,
    question: '구월',
    options: ['iyul', 'sentabr', 'avgust', 'may'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 3.2,
    question: '시월',
    options: ['oktabr', 'iyul', 'avgust', 'may'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 3.2,
    question: '십일월',
    options: ['iyun', 'may', 'noyabr', 'iyul'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 15,
    unitNumber: 3.2,
    question: '십이월',
    options: ['avgust', 'iyul', 'dekabr', 'may'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 16,
    unitNumber: 3.2,
    question: '일',
    options: ['kun', 'oy', 'nechanchi', 'sana'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 3.2,
    question: '일일',
    options: ['birinchi kun', '1-kun', '5-kun', 'kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 18,
    unitNumber: 3.2,
    question: '오일',
    options: ['1-kun', '5-kun', '2-kun', 'kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 3.2,
    question: '십일',
    options: ['15-kun', '20-kun', '25-kun', '10-kun'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 20,
    unitNumber: 3.2,
    question: '십오일',
    options: ['20-kun', '15-kun', '25-kun', 'birinchi kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 21,
    unitNumber: 3.2,
    question: '이십일',
    options: ['15-kun', '2-kun', '20-kun', '12-kun'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 22,
    unitNumber: 3.2,
    question: '이십오일',
    options: ['20-kun', '15-kun', '22-kun', '25-kun'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 23,
    unitNumber: 3.2,
    question: '삼십일',
    options: ['30-kun', '25-kun', '20-kun', '13-kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 3.2,
    question: '삼십일일',
    options: ['31-kun', '30-kun', '3-kun', '25-kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 3.2,
    question: '어제',
    options: ['ertaga', 'kecha', 'sana', 'bugun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 26,
    unitNumber: 3.2,
    question: '오늘',
    options: ['bugun', 'kecha', 'sana', 'ertaga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 3.2,
    question: '내일',
    options: ['kecha', 'sana', 'ertaga', 'bugun'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 28,
    unitNumber: 3.2,
    question: '지난주',
    options: ['o`tgan hafta', 'shu hafta', 'kelasi hafta', 'oy'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 3.2,
    question: '이번 주',
    options: ['o`tgan hafta', 'kelasi hafta', 'oy', 'shu hafta'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 30,
    unitNumber: 3.2,
    question: '다음 주',
    options: ['shu hafta', 'o`tgan hafta', 'kelasi hafta', 'oy'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 31,
    unitNumber: 3.2,
    question: '요일',
    options: ['hafta kunlari', 'darsda qatnashmoq', 'ish kunlari', 'oy'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 3.2,
    question: '일요일',
    options: ['dushanba', 'chorshanba', 'shanba', 'yakshanba'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 33,
    unitNumber: 3.2,
    question: '월요일',
    options: ['dushanba', 'yakshanba', 'seshanba', 'chorshanba'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 34,
    unitNumber: 3.2,
    question: '화요일',
    options: ['seshanba', 'yakshanba', 'chorshanba', 'dushanba'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 35,
    unitNumber: 3.2,
    question: '수요일',
    options: ['yakshanba', 'chorshanba', 'seshanba', 'dushanba'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 36,
    unitNumber: 3.2,
    question: '목요일',
    options: ['dushanba', 'yakshanba', 'seshanba', 'payshanba'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 37,
    unitNumber: 3.2,
    question: '금요일',
    options: ['juma', 'yakshanba', 'seshanba', 'chorshanba'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 38,
    unitNumber: 3.2,
    question: '토요일',
    options: ['yakshanba', 'shanba', 'seshanba', 'chorshanba'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 39,
    unitNumber: 3.2,
    question: '주말',
    options: ['dam olish kunlari', 'ish kunlari', 'sana', 'oy'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 40,
    unitNumber: 3.2,
    question: '평일=주중',
    options: ['sana', 'oy', 'ish kunlari', 'dam olmoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 41,
    unitNumber: 3.2,
    question: '수업을 하다',
    options: ['darsda qatnashmoq', 'dam olmoq', 'imtihon olmoq', 'o\'rgatmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 42,
    unitNumber: 3.2,
    question: '쉬다',
    options: ['imtihon olmoq', 'vaqt', 'dam olmoq', 'darsda qatnashmoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 43,
    unitNumber: 3.2,
    question: '숙제하다',
    options: [
      'uy vazifasini bajaromoq',
      'darsda qatnashmoq',
      'vaqtni olmoq',
      'dam olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 44,
    unitNumber: 3.2,
    question: '배우다',
    options: ['o\'rgatmoq', 'darsda qatnashmoq', 'dam olmoq', 'o`rganmoq'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 45,
    unitNumber: 3.2,
    question: '방학',
    options: ['ta`til', 'darsda qatnashmoq', 'tanaffus', 'vaqt'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 46,
    unitNumber: 3.2,
    question: '영어',
    options: [
      'oy',
      'ingliz tili',
      'rus tili',
      'sayohat',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 47,
    unitNumber: 3.2,
    question: '가르치다',
    options: [
      'o\'rganmoq',
      'ta\'til',
      'o`rgatmoq',
      'darsda qatnashmoq',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 48,
    unitNumber: 3.2,
    question: '태권도',
    options: ['sport', 'sana', 'oy', 'takvondo'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 49,
    unitNumber: 3.2,
    question: '음식',
    options: ['ovqat', 'darsda', 'oshxona', 'musiqa'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 50,
    unitNumber: 3.2,
    question: '중국어',
    options: ['ingliz tili', 'xitoy tili', 'dars', 'Xitoy'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 51,
    unitNumber: 3.2,
    question: '김밥',
    options: ['kimchi', 'ta\'lim', 'oy', 'kimpap'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 52,
    unitNumber: 3.2,
    question: '수영',
    options: ['suzish', 'suzish havzasi', 'sport', 'suzmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 53,
    unitNumber: 3.2,
    question: '라면',
    options: ['dars', 'sana', 'ramyon', 'oy'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 54,
    unitNumber: 3.2,
    question: '요즘',
    options: ['hafta kunlari', 'bu hafta', ' keyingi oy', 'shu kunlarda'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 55,
    unitNumber: 3.2,
    question: '바쁘다',
    options: ['ishlanoq', 'band', 'chiroyli', 'shovqin'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 56,
    unitNumber: 3.2,
    question: '기분',
    options: ['kayfiyat', 'raqam', 'kelasi oy', 'bu hafta'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 57,
    unitNumber: 3.2,
    question: '날씨',
    options: ['ob-havo', 'dars', 'sana', 'o\'tgan oy'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 58,
    unitNumber: 3.2,
    question: '예쁘다',
    options: ['shovqin', 'band', 'uzun', 'chiroyli'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 59,
    unitNumber: 3.2,
    question: '비',
    options: ['ob-havo', 'yomg`ir', 'quyoshli', 'oy'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 60,
    unitNumber: 3.2,
    question: '이/가 있다',
    options: ['bor', 'darsda bo\'lmoq', 'kulmoq', 'bo\'lmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 61,
    unitNumber: 3.2,
    question: '매일',
    options: ['ertaga', 'har hafta', 'har oy', 'har kuni'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 62,
    unitNumber: 3.2,
    question: '생일',
    options: [
      'tug`ilgan kun',
      'tug`ilgan kun bazmi',
      'tug`ilmoq',
      'tug`ilgan kun torti'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 63,
    unitNumber: 3.2,
    question: '생일 파티',
    options: ['tug`ilmoq', 'tug`ilgan kun bazmi', 'tug`ilgan kun torti' 'sana'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 64,
    unitNumber: 3.2,
    question: '여행을 하다',
    options: ['sayohat qilmoq', 'sayr qimoq', 'tog\'ga chiqmoq', 'dam olish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 65,
    unitNumber: 3.2,
    question: '휴가',
    options: ['ta`til(umumiy)', 'darsdan chiqmoq', 'dam olmoq', 'hafta oxiri'],
    correctOptionIndex: 0,
  ),

  // #3.3 Unit

  QuizTest(
    id: 1,
    unitNumber: 3.3,
    question: '시간',
    options: ['Vaqti', 'Soat', 'Davomiyligi', 'Vaqt'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 2,
    unitNumber: 3.3,
    question: '그저께',
    options: ['Kechadan avvalgi kunga', 'Kecha', 'Shu kun', 'Bugun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 3.3,
    question: '어제',
    options: ['Vaqt', 'Kecha', 'Bugun', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 4,
    unitNumber: 3.3,
    question: '오늘',
    options: ['Bugun', 'Kechirasiz', 'Soat', 'Vaqt'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 3.3,
    question: '내일',
    options: ['Ertaga', 'Shu kun', 'Bugun', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 6,
    unitNumber: 3.3,
    question: '모레',
    options: ['Indin', 'Kechirasiz', 'Kechadan avvalgi kunga', 'Shu kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 3.3,
    question: '지난주',
    options: ['Shu hafta', 'Kechadan avvalgi kunga', 'Indin', 'O`tgan hafta'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 8,
    unitNumber: 3.3,
    question: '이번 주',
    options: ['Shu hafta', 'O`tgan hafta', 'Bugun', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 9,
    unitNumber: 3.3,
    question: '다음 주',
    options: ['Kelasi hafta', 'Ertaga', 'Indin', 'Shu kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 10,
    unitNumber: 3.3,
    question: '지난달',
    options: ['O`tgan oy', 'Indin', 'Shu hafta', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 11,
    unitNumber: 3.3,
    question: '이번 달',
    options: ['Shu oy', 'Kelasi hafta', 'Kechadan avvalgi kunga', 'Indin'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 3.3,
    question: '다음 달',
    options: ['Kelasi oy', 'Ertaga', 'Indin', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 3.3,
    question: '작년',
    options: ['O`tgan yil', 'Indin', 'Ertaga', 'Shu oy'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 3.3,
    question: '올해',
    options: ['Shu yil', 'Kelasi oy', 'Indin', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 15,
    unitNumber: 3.3,
    question: '내년',
    options: ['Kelasi yil', 'Shu hafta', 'Kechadan avvalgi kunga', 'Indin'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 16,
    unitNumber: 3.3,
    question: '취미 활동',
    options: [
      'Qiziqarli mashg`ulot',
      'Indin',
      'Ertaga',
      'Kechadan avvalgi kunga'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 3.3,
    question: '등산을 하다',
    options: ['Toqqa chiqmoq', 'Indin', 'Shu hafta', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 3.3,
    question: '여행을 하다',
    options: ['Sayohat qilmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 3.3,
    question: '낚시를 하다',
    options: ['Baliq ovlamoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 20,
    unitNumber: 3.3,
    question: '독서를 하다',
    options: ['Mutoala qilmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 3.3,
    question: '쇼핑을 하다',
    options: ['Harid qilmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 3.3,
    question: '차',
    options: ['Choy', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 3.3,
    question: '산책을 하다',
    options: ['Sayr qilmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 3.3,
    question: '지금',
    options: ['Hozir', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 3.3,
    question: '물',
    options: ['Suv', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 3.3,
    question: '불고기',
    options: ['Bulkoqi', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 3.3,
    question: '(옷을) 입다',
    options: ['(Kiyim) kiyinmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 3.3,
    question: '화장을 하다',
    options: ['Pardoz qilmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 3.3,
    question: '세수를 하다',
    options: [
      'Yuz-qo`lini yuvmoq',
      'Indin',
      'Ertaga',
      'Kechadan avvalgi kunga'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 3.3,
    question: '이를 닦다',
    options: ['Tishini yuvmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 31,
    unitNumber: 3.3,
    question: '청소를 하다',
    options: ['Uy tozalamoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 3.3,
    question: '사다',
    options: ['Sotib olmoq', 'Indin', 'Ertaga', 'Kechadan avvalgi kunga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 33,
    unitNumber: 3.3,
    question: '(시간을) 잘 보내다',
    options: [
      '(Vaqt) yaxshi o`tqazmoq',
      'Indin',
      'Ertaga',
      'Kechadan avvalgi kunga'
    ],
    correctOptionIndex: 0,
  ),

  // #4.1 Unit

  QuizTest(
    id: 1,
    unitNumber: 4.1,
    question: '위치',
    options: ['Lakatsa/Joylashuv', 'Usti', 'Osti', 'Oldi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 4.1,
    question: '위',
    options: ['Oldi', 'Osti', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 3,
    unitNumber: 4.1,
    question: '아래(밑)',
    options: ['Osti', 'Usti', 'Oldi', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 4.1,
    question: '앞',
    options: ['Oldi', 'Usti', 'Lakatsa/Joylashuv', 'Osti'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 4.1,
    question: '뒤',
    options: ['Oldi', 'Osti', 'Lakatsa/Joylashuv', 'Usti'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 4.1,
    question: '안',
    options: ['Lakatsa/Joylashuv', 'Osti', 'Oldi', 'Usti'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 7,
    unitNumber: 4.1,
    question: '밖',
    options: ['Lakatsa/Joylashuv', 'Oldi', 'Usti', 'Osti'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 4.1,
    question: '옆',
    options: ['Oldi', 'Lakatsa/Joylashuv', 'Usti', 'Osti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 9,
    unitNumber: 4.1,
    question: '사이',
    options: ['Osti', 'Lakatsa/Joylashuv', 'Usti', 'Oldi'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 10,
    unitNumber: 4.1,
    question: '사물',
    options: ['Lakatsa/Joylashuv', 'Usti', 'Oldi', 'Buyum'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 11,
    unitNumber: 4.1,
    question: '교실',
    options: ['Oldi', 'Sinfxona', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 4.1,
    question: '문',
    options: ['Oldi', 'Eshik', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 4.1,
    question: '창문',
    options: ['Deraza', 'Usti', 'Oldi', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 4.1,
    question: '칠판',
    options: ['Lakatsa/Joylashuv', 'Oldi', 'Doska', 'Usti'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 15,
    unitNumber: 4.1,
    question: '지우개',
    options: ['Lakatsa/Joylashuv', 'O`chirg`ich', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 16,
    unitNumber: 4.1,
    question: '지도',
    options: ['Lakatsa/Joylashuv', 'Oldi', 'Xarita', 'Usti'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 17,
    unitNumber: 4.1,
    question: '시계',
    options: ['Soat', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 4.1,
    question: '달력',
    options: ['Kalendar', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 4.1,
    question: '컴퓨터',
    options: ['Lakatsa/Joylashuv', 'Usti', 'Oldi', 'Kompyuter'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 20,
    unitNumber: 4.1,
    question: '책상',
    options: ['Parta', 'Usti', 'Oldi', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 4.1,
    question: '의자',
    options: ['Stul', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 4.1,
    question: '공책',
    options: ['Lakatsa/Joylashuv', 'Oldi', 'Daftar', 'Usti'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 23,
    unitNumber: 4.1,
    question: '연필',
    options: ['Lakatsa/Joylashuv', 'Qalam', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 24,
    unitNumber: 4.1,
    question: '볼펜',
    options: ['Ro`chka', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 4.1,
    question: '사전',
    options: ['Lug`at', 'Usti', 'Oldi', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 4.1,
    question: '휴대폰',
    options: ['Telefon', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 4.1,
    question: '누가(누구가)',
    options: ['Lakatsa/Joylashuv', 'Kim', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 28,
    unitNumber: 4.1,
    question: '전자 사전',
    options: ['Eliktron lug`at', 'Usti', 'Oldi', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 4.1,
    question: '학교',
    options: ['Lakatsa/Joylashuv', 'Maktab', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 30,
    unitNumber: 4.1,
    question: '필통',
    options: ['Lakatsa/Joylashuv', 'Usti', 'Oldi', 'Qalamdon'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 31,
    unitNumber: 4.1,
    question: '도서관',
    options: ['Lakatsa/Joylashuv', 'Kutubxona', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 32,
    unitNumber: 4.1,
    question: '식당',
    options: ['Restoran', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 33,
    unitNumber: 4.1,
    question: '가방',
    options: ['Lakatsa/Joylashuv', 'Sumka', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 34,
    unitNumber: 4.1,
    question: '구두',
    options: ['Tufli', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 35,
    unitNumber: 4.1,
    question: '그런데',
    options: ['Lakin, aytgancha', 'Oldi', 'Usti', 'Lakatsa/Joylashuv'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 36,
    unitNumber: 4.1,
    question: '국제 교육관',
    options: ['Lakatsa/Joylashuv', 'Xalqaro ta`lim markazi', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 37,
    unitNumber: 4.1,
    question: '학생들',
    options: ['Lakatsa/Joylashuv', 'O`quvchilar', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 38,
    unitNumber: 4.1,
    question: '기숙사',
    options: ['Lakatsa/Joylashuv', 'Oldi', 'Yotoqxona', 'Usti'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 39,
    unitNumber: 4.1,
    question: '편의점',
    options: ['Lakatsa/Joylashuv', 'Oldi', '24/7 do`kon', 'Usti'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 40,
    unitNumber: 4.1,
    question: '꽃집',
    options: ['Lakatsa/Joylashuv', 'Oldi', 'Gul do`kon', 'Usti'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 41,
    unitNumber: 4.1,
    question: '우체국',
    options: ['Lakatsa/Joylashuv', 'Pochta', 'Oldi', 'Usti'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 42,
    unitNumber: 4.1,
    question: '운동장',
    options: ['Lakatsa/Joylashuv', 'Oldi', 'Sport maydoni/Stadion', 'Usti'],
    correctOptionIndex: 2,
  ),

  // 4.2 Unit
  QuizTest(
    id: 1,
    unitNumber: 4.2,
    question: '장소',
    options: ['Joy', 'Oid/Bog`liq', 'Fe`l', 'Kutubxona'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 4.2,
    question: '관련',
    options: ['Joy', 'Oid/Bog`liq', 'Fe`l', 'Kutubxona'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 3,
    unitNumber: 4.2,
    question: '동사',
    options: ['Joy', 'Oid/Bog`liq', 'Fe`l', 'Kutubxona'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 4,
    unitNumber: 4.2,
    question: '도서관',
    options: ['Joy', 'Oid/Bog`liq', 'Fe`l', 'Kutubxona'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 5,
    unitNumber: 4.2,
    question: '책을 읽다',
    options: [
      'Kitob o`qimoq',
      'Sport bilan shug`illanmoq',
      'Kutubxona',
      'Gipermarket/Unvermak'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 4.2,
    question: '운장장',
    options: ['Joy', 'Oid/Bog`liq', 'Stadion', 'Kitob o`qimoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 7,
    unitNumber: 4.2,
    question: '운동을 하다',
    options: [
      'Joy',
      'Sport bilan shug`illanmoq',
      'Oid/Bog`liq',
      'Kitob o`qimoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 8,
    unitNumber: 4.2,
    question: '편의점',
    options: [
      '27/7 do`kon',
      'Kitob sotib olmoq',
      'Kridet olmoq',
      'Xat yubormoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 4.2,
    question: '물건을 사다',
    options: [
      '27/7 do`kon',
      'Narsa sotib olmoq',
      'Kridet olmoq',
      'Xat yubormoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 10,
    unitNumber: 4.2,
    question: '백화점',
    options: [
      '27/7 do`kon',
      'Gipermarket/Unvermak',
      'Kridet olmoq',
      'Xat yubormoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 11,
    unitNumber: 4.2,
    question: '쇼핑을 하다',
    options: [
      '27/7 do`kon',
      'Shopping(Xarid) qilmoq',
      'Kridet olmoq',
      'Xat yubormoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 4.2,
    question: '서점',
    options: ['27/7 do`kon', 'Kitob magazini', 'Kridet olmoq', 'Xat yubormoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 4.2,
    question: '책을 사다',
    options: [
      '27/7 do`kon',
      'Kitob sotib olmoq',
      'Kridet olmoq',
      'Xat yubormoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 14,
    unitNumber: 4.2,
    question: '은행',
    options: ['Bank', 'Kitob magazini', 'Kridet olmoq', 'Xat yubormoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 4.2,
    question: '돈을 찾다',
    options: ['Bank', 'Pul maydalamoq', 'Kridet olmoq', 'Xat yubormoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 16,
    unitNumber: 4.2,
    question: '돈을 빌리다',
    options: ['Bank', 'Kridet olmoq', 'Pul maydalamoq', 'Xat yubormoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 17,
    unitNumber: 4.2,
    question: '우체국',
    options: ['Pochta', 'Kridet olmoq', 'Pul maydalamoq', 'Xat yubormoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 4.2,
    question: '편지를 보내다',
    options: ['Pochta', 'Xat yubormoq', 'Pul maydalamoq', 'Kridet olmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 4.2,
    question: '소포를 보내다',
    options: [
      'Pochta(yuki) yubormoq',
      'Xat yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 20,
    unitNumber: 4.2,
    question: '영화관',
    options: ['Kino teatr', 'Xat yubormoq', 'Pul maydalamoq', 'Kridet olmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 4.2,
    question: '영화를 보다',
    options: [
      'Kino ko`rmoq',
      'Xat yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq',
      'Pochta(yuki) yubormoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 4.2,
    question: '주스',
    options: [
      'Sharbat',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 4.2,
    question: '일기를 쓰다',
    options: [
      'Kundalik yozmoq',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 4.2,
    question: '손',
    options: [
      'Qo`l',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 4.2,
    question: '씻다',
    options: [
      'Yuvm',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 4.2,
    question: '방',
    options: [
      'Xona',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 4.2,
    question: '공원',
    options: [
      'Bog`',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 4.2,
    question: '길다',
    options: [
      'Uzun',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 4.2,
    question: '꽃',
    options: ['Gul', 'Pochta(yuki) yubormoq', 'Pul maydalamoq', 'Kridet olmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 4.2,
    question: '시험',
    options: [
      'Imtihon',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 31,
    unitNumber: 4.2,
    question: '그래서',
    options: [
      'Shuning uchun',
      'Pochta(yuki) yubormoq',
      'Pul maydalamoq',
      'Kridet olmoq'
    ],
    correctOptionIndex: 0,
  ),

  // #4.3 Unit
  QuizTest(
    id: 1,
    unitNumber: 4.3,
    question: '방향',
    options: ['Yunalish', 'Qayer?', 'Bu yer/Bu taraf', 'U yer/U taraf'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 4.3,
    question: '어디',
    options: ['Qayer?', 'Yunalish', 'Bu yer/Bu taraf', 'U yer/U taraf'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 4.3,
    question: '여기/이쪽',
    options: ['Bu yer/Bu taraf', 'Qayer?', 'Yunalish', 'U yer/U taraf'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 4.3,
    question: '거기/그쪽',
    options: ['U yer/U taraf', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 4.3,
    question: '저기/저쪽',
    options: ['Anavi yer/Anavi taraf', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 4.3,
    question: '오른쪽',
    options: ['O`ng taraf', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 4.3,
    question: '왼쪽',
    options: ['Chap taraf', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 4.3,
    question: '근처',
    options: ['Yaqin atrof/Yon atrof', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 4.3,
    question: '건너편(맞은편)',
    options: ['Qarama-qarshi taraf', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 10,
    unitNumber: 4.3,
    question: '북쪽',
    options: ['Shimol(taraf)', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 4.3,
    question: '남쪽',
    options: ['Janub', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 4.3,
    question: '서쪽',
    options: ['G`arb', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 4.3,
    question: '동쪽',
    options: ['Sharq', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 4.3,
    question: '회사',
    options: ['Firma(Office)', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 4.3,
    question: '다니다',
    options: [
      'Qatnamoq/Borib kelmoq/Ishlamoq',
      'Qayer?',
      'Bu yer/Bu taraf',
      'Yunalish'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 4.3,
    question: '시장',
    options: ['Bozor', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 4.3,
    question: '커피숍',
    options: ['Qahvaxona', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 4.3,
    question: '앉다',
    options: ['O`tirmoq', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 4.3,
    question: '찾다',
    options: ['Qidirmoq', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 20,
    unitNumber: 4.3,
    question: '타다',
    options: ['Minmoq', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 4.3,
    question: '정류장',
    options: ['(Avtobus)Bekati', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 4.3,
    question: '잡지',
    options: ['Jurnal', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 4.3,
    question: '먼저',
    options: ['Avvalo/Birinchi', 'Qayer?', 'Bu yer/Bu taraf', 'bosh'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 4.3,
    question: '정문',
    options: [
      'Old eshik/Asosiy darvoza',
      'Qayer?',
      'Bu yer/Bu taraf',
      'Yunalish'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 4.3,
    question: '다시',
    options: ['Yana/Qayta', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 4.3,
    question: '그리고',
    options: ['Va/So`ng', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 4.3,
    question: '박물관',
    options: ['Muzey', 'Qayer?', 'Bu yer/Bu taraf', 'Yunalish'],
    correctOptionIndex: 0,
  ),

  // #5.1 Unit
  QuizTest(
    id: 1,
    unitNumber: 5.1,
    question: '계절과 날씨',
    options: ['Fasl va ob-havo', 'Bahor', 'Iliq', 'Yoz'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 5.1,
    question: '봄',
    options: ['Bahor', 'Fasl va ob-havo', 'Iliq', 'Yoz'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 5.1,
    question: '따뜻하다',
    options: ['Iliq', 'Bahor', 'Fasl va ob-havo', 'Yoz'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 5.1,
    question: '여름',
    options: ['Yoz', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 5.1,
    question: '덥다',
    options: ['Issiq', 'Bahor', 'Fasl va ob-havo', 'Yoz'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 5.1,
    question: '가을',
    options: ['Kuz', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 5.1,
    question: '시원하다',
    options: ['Salqin', 'Bahor', 'Fasl va ob-havo', 'Yoz'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 5.1,
    question: '겨울',
    options: ['Qish', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 5.1,
    question: '춥다',
    options: ['Sovuq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 10,
    unitNumber: 5.1,
    question: '형용사',
    options: ['Sifat', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 5.1,
    question: '맵다',
    options: ['Achchiq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 5.1,
    question: '좁다',
    options: ['Tor', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 5.1,
    question: '가볍다',
    options: ['Yengil', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 5.1,
    question: '무겁다',
    options: ['Og\'ir', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 5.1,
    question: '아름답다',
    options: ['Chiroyli', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 5.1,
    question: '동사',
    options: ['Fe\'l', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 5.1,
    question: '도움을 주다',
    options: ['Yordam bermoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 5.1,
    question: '입다',
    options: ['Kiyamoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 5.1,
    question: '잡다',
    options: ['Tutmoq/Ushlamoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 20,
    unitNumber: 5.1,
    question: '바다',
    options: ['Dengiz', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 5.1,
    question: '김치찌개',
    options: ['Kimchi sho\'rva', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 5.1,
    question: '좀',
    options: ['Biroz', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 5.1,
    question: '자전거를 타다',
    options: ['Velik haydamoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 5.1,
    question: '배가 부르다',
    options: ['Qorni to\'ymoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 5.1,
    question: '택시를 타다',
    options: ['Taksiga o\'tirmoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 5.1,
    question: '자주',
    options: ['Tez-tez', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 5.1,
    question: '우산',
    options: ['Soyabon', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 5.1,
    question: '가지고 가다',
    options: ['Olib ketmoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 5.1,
    question: '늦게',
    options: ['Kech', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 5.1,
    question: '많이',
    options: ['Ko`p', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 31,
    unitNumber: 5.1,
    question: '남자 친구',
    options: ['Yigit o`rtoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 5.1,
    question: '졸업을 하다',
    options: ['O`qishni bitirmoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 33,
    unitNumber: 5.1,
    question: '취직을 하다',
    options: ['Ishga kirmoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 5.1,
    question: '더럽다',
    options: ['Kir/Iflos', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 35,
    unitNumber: 5.1,
    question: '축구를 하다',
    options: ['Fudbol o`ynamoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 36,
    unitNumber: 5.1,
    question: '빨래를 하다',
    options: ['Kir yuvmoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 37,
    unitNumber: 5.1,
    question: '외출을 하다',
    options: ['Ko`chaga chiqmoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 38,
    unitNumber: 5.1,
    question: '컴퓨터 게임을 하다',
    options: ['Kompyuterda o`yin o`ynamoq', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 39,
    unitNumber: 5.1,
    question: '건강',
    options: ['Sog`lik', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 40,
    unitNumber: 5.1,
    question: '열',
    options: [
      'Astoyidil/ Qattiq(harakatga nisbatan)',
      'Bahor',
      'Fasl va ob-havo',
      'Iliq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 41,
    unitNumber: 5.1,
    question: '맑다',
    options: ['Tiniq/Musaffo', 'Bahor', 'Fasl va ob-havo', 'Iliq'],
    correctOptionIndex: 0,
  ),

  // #5.2 Unit
  QuizTest(
    id: 1,
    unitNumber: 5.2,
    question: '취미 활동',
    options: [
      'hobbiy mashg\'ulotlar',
      'sayr qilmoq',
      'o\'yin o\'ynamoq (online)',
      'internetda vaqt o\'tkazmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 5.2,
    question: '산책을 하다',
    options: [
      'o\'yin o\'ynamoq (online)',
      'hobbiy mashg\'ulotlar',
      'sayr qilmoq',
      'internetda vaqt o\'tkazmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 3,
    unitNumber: 5.2,
    question: '게임을 하다',
    options: [
      'hobbiy mashg\'ulotlar',
      'sayr qilmoq',
      'internetda vaqt o\'tkazmoq',
      'o\'yin o\'ynamoq (online)'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 4,
    unitNumber: 5.2,
    question: '인터넷을 하다',
    options: [
      'o\'yin o\'ynamoq (online)',
      'hobbiy mashg\'ulotlar',
      'sayr qilmoq',
      'internetda vaqt o\'tkazmoq'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 5,
    unitNumber: 5.2,
    question: '춤을 추다',
    options: [
      'raqsga tushmoq',
      'uxlamoq',
      'sayr qilmoq',
      'tush ko\'rmoq',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 5.2,
    question: '기타를 치다',
    options: [
      'raqsga tushmoq',
      'uxlamoq',
      'gitara chalmoq',
      'sayr qilmoq',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 7,
    unitNumber: 5.2,
    question: '그림을 그리다',
    options: [
      'raqsga tushmoq',
      'uxlamoq',
      'rasm chizmoq',
      'tush ko\'rmoq',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 8,
    unitNumber: 5.2,
    question: '사진을 찍다',
    options: [
      'rasmga olmoq',
      'uxlamoq',
      'rasm chizmoq',
      'tush ko\'rmoq',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 5.2,
    question: '배드민턴을 치다',
    options: [
      'raqsga tushmoq',
      'uxlamoq',
      'gitara chalmoq',
      'badminton o\'ynamoq',
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 10,
    unitNumber: 5.2,
    question: '동사',
    options: ['fe\'l', 'sifat', 'uka', 'ot'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 5.2,
    question: '듣다',
    options: [
      'eshitmoq',
      'uxlamoq',
      'gapirmoq',
      'o\'ynamoq',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 5.2,
    question: '걷다',
    options: [
      'mashq qilmoq',
      'raqsga tushmoq',
      'uxlamoq',
      'piyoda yurmoq',
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 13,
    unitNumber: 5.2,
    question: '묻다',
    options: [
      'so\'ramoq',
      'piyoda yurmoq',
      'mashq qilmoq',
      'raqsga tushmoq',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 5.2,
    question: '싣다',
    options: [
      'eshitmoq',
      'mashq qilmoq',
      'raqsga tushmoq',
      'yuklamoq',
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 15,
    unitNumber: 5.2,
    question: '닫다',
    options: [
      'piyoda yurmoq',
      'mashq qilmoq',
      'yopmoq',
      'raqsga tushmoq',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 16,
    unitNumber: 5.2,
    question: '받다',
    options: [
      'olmoq / qabul qilmoq',
      'piyoda yurmoq',
      'mashq qilmoq',
      'raqsga tushmoq',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 5.2,
    question: '비싸다',
    options: [
      'qimmat',
      'arzon',
      'narx',
      'narxi pasaymoq',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 5.2,
    question: '버스',
    options: [
      'metro',
      'avtobus',
      'mashina',
      'poyezd',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 5.2,
    question: '싸다',
    options: [
      'qimmat',
      'arzon',
      'narx',
      'narxi pasaymoq',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 20,
    unitNumber: 5.2,
    question: '떡볶이',
    options: [
      'Tokbukki',
      'qimmat',
      'arzon',
      'narx',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 5.2,
    question: '가끔',
    options: [
      'hech qachon',
      'tez-tez',
      'har doim',
      'ba\'zan',
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 22,
    unitNumber: 5.2,
    question: '술',
    options: [
      'suv',
      'hobbiy',
      'aroq',
      'qush',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 23,
    unitNumber: 5.2,
    question: '콜라',
    options: [
      'cola',
      'suv',
      'aroq',
      'tez-tez',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 5.2,
    question: '배가 고프다',
    options: [
      'mashq qilmoq',
      'raqsga tushmoq',
      'qorni och bo\'lmoq',
      'sayr qilmoq',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 25,
    unitNumber: 5.2,
    question: '시내',
    options: [
      'shahar markazi',
      'sayohat',
      'yangi',
      'avtobus',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 5.2,
    question: '믿다',
    options: [
      'mashq qilmoq',
      'ishonmoq',
      'raqsga tushmoq',
      'vada bermoq',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 27,
    unitNumber: 5.2,
    question: '길',
    options: [
      'katta',
      'xarita',
      'yo\'l',
      'qisqa',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 28,
    unitNumber: 5.2,
    question: '잘',
    options: [
      'charchamoq',
      'yomon',
      'sayr qilmoq',
      'yaxshi',
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 29,
    unitNumber: 5.2,
    question: '모르다',
    options: [
      'bilmaslik',
      'bosh',
      'so\'ramoq',
      'bosh kiyim',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 5.2,
    question: '아주머니',
    options: ['ona', 'xola', 'amaki', 'aka'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 31,
    unitNumber: 5.2,
    question: '선물',
    options: [
      'sovg\'a',
      'hobbiy',
      'topshiriq',
      'taklifnoma',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 5.2,
    question: '에어컨',
    options: [
      'televizor',
      'konditsioner',
      'moslama',
      'muzlatgich',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 33,
    unitNumber: 5.2,
    question: '켜다',
    options: [
      'yoqmoq / qo\'shmoq',
      'harkat qilmoq',
      'sayr qilmoq',
      'kelmoq',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 5.2,
    question: '하루 종일',
    options: [
      'tez-tez',
      'hafta kuni',
      'kun davomida',
      'telefonda gaplashmoq',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 35,
    unitNumber: 5.2,
    question: '정말',
    options: ['rostan / juda', 'tez-tez', 'har doim', 'lekin / ammo'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 36,
    unitNumber: 5.2,
    question: '피곤하다',
    options: [
      'bilmaslik',
      'charchagan',
      'sayr qilish',
      'boshlash',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 37,
    unitNumber: 5.2,
    question: '체육관',
    options: [
      'sport zal',
      'metro bekati',
      'avtobus bekati',
      'teatr',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 38,
    unitNumber: 5.2,
    question: '앞으로',
    options: [
      'har doim',
      'og\'rimoq',
      'tez-tez',
      'kelajakda',
    ],
    correctOptionIndex: 3,
  ),

  // #5.3 Unit
  QuizTest(
    id: 1,
    unitNumber: 5.3,
    question: '여행지',
    options: ['joylashuv', 'sayohat joylari', 'daryo', 'sayohat'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 2,
    unitNumber: 5.3,
    question: '산',
    options: ['dengiz', 'daryo', 'to\'g', 'ko\'l'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 3,
    unitNumber: 5.3,
    question: '바다',
    options: ['daryo', 'to\'g', 'ko\'l', 'dengiz'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 4,
    unitNumber: 5.3,
    question: '강',
    options: ['ko\'l', 'dengiz', 'daryo', 'to\'g'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 5,
    unitNumber: 5.3,
    question: '호수',
    options: ['daryo', 'to\'g', 'ko\'l', 'dengiz'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 6,
    unitNumber: 5.3,
    question: '캠핑을 하다',
    options: [
      'dieta qilmoq',
      'lagerga bormoq',
      'chang\'i uchmoq',
      'uchrashuvga bormoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 7,
    unitNumber: 5.3,
    question: '아르바이트를 하다',
    options: [
      'dieta qilmoq',
      'lagerga bormoq',
      'kunlik ish qilmoq',
      'pul topmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 8,
    unitNumber: 5.3,
    question: '데이트를 하다',
    options: [
      'uchrashuvga bormoq',
      'dieta qilmoq',
      'lagerga bormoq',
      'kunlik ish qilmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 5.3,
    question: '운전 연습을 하다',
    options: [
      'lagerga bormoq',
      'haydashni mashq qilmoq',
      'uchrashuvga bormoq',
      'dieta qilmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 10,
    unitNumber: 5.3,
    question: '스키를 타다',
    options: [
      'dieta qilmoq',
      'lagerga bormoq',
      'chang\'i uchmoq',
      'uchrashuvga bormoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 11,
    unitNumber: 5.3,
    question: '살다',
    options: ['sotib olmoq', 'yashamoq', 'sotmoq', 'kulmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 5.3,
    question: '다이어트를 하다',
    options: [
      'lagerga bormoq',
      'dieta qilmoq',
      'chang\'i uchmoq',
      'uchrashuvga bormoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 5.3,
    question: '얼마',
    options: ['qanday', 'nima', 'qancha', 'kim'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 14,
    unitNumber: 5.3,
    question: '년',
    options: ['kun', 'yil', 'oy', 'hafta'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 15,
    unitNumber: 5.3,
    question: '기다리다',
    options: ['og\'rimoq', 'kutmoq', 'tugatmoq', 'o\'ynamoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 16,
    unitNumber: 5.3,
    question: '메시지를 보내다',
    options: ['jo\'namoq', 'xabar', 'xabar jo\'natmoq', 'kutmoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 17,
    unitNumber: 5.3,
    question: '돌아가다',
    options: ['qaytib bormoq', 'chiqmoq', 'kelmoq', 'kirmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 5.3,
    question: '아이스크림',
    options: ['qor', 'muzqaymoq', 'yangi', 'dori'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 5.3,
    question: '배',
    options: ['qo\'shiq', 'bosh', 'dori', 'qorin'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 20,
    unitNumber: 5.3,
    question: '아프다',
    options: ['kulmoq', 'band bo\'lmoq', 'og\'rimoq', 'o\'ynamoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 21,
    unitNumber: 5.3,
    question: '머리',
    options: ['bosh', 'dori', 'yuk', 'mashina'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 5.3,
    question: '약',
    options: ['bosh', 'yuk', 'mashina', 'dori'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 23,
    unitNumber: 5.3,
    question: '새',
    options: ['sovg\'a', 'yangi', 'daryo', 'pul'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 24,
    unitNumber: 5.3,
    question: '동대문 시장',
    options: ['yangi', 'krasofka', 'Tongdemun bozori', 'bosh'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 25,
    unitNumber: 5.3,
    question: '봄옷',
    options: ['bosh kiyim', 'qorin', 'yangi', 'bahorgi kiyim'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 26,
    unitNumber: 5.3,
    question: '단어',
    options: ['manzara', 'so\'z', 'til', 'qo\'shiq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 27,
    unitNumber: 5.3,
    question: '운동화',
    options: ['krasofka', 'sport', 'sport zal', 'mashq qilmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 5.3,
    question: '노래',
    options: ['manzara', 'so\'z', 'til', 'qo\'shiq'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 29,
    unitNumber: 5.3,
    question: '놀다',
    options: ['kulmoq', 'o\'ynamoq', 'tinglamoq', 'qo\'shiq aytmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 30,
    unitNumber: 5.3,
    question: '잘하다',
    options: ['o\'ynamoq', 'tinglamoq', 'yaxshi qilmoq', 'qo\'shiq aytmoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 31,
    unitNumber: 5.3,
    question: '자동차',
    options: ['metro', 'mashina', 'avtobus', 'poyezd'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 32,
    unitNumber: 5.3,
    question: '제주도',
    options: ['yangi', 'sayohat', 'Cheju oroli', 'manzara'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 33,
    unitNumber: 5.3,
    question: '경치',
    options: ['manzara', 'so\'z', 'til', 'qo\'shiq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 5.3,
    question: '세계 여행',
    options: ['orol', 'dunyo bo\'ylab sayohat', 'bormoq', 'sayr qilmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 35,
    unitNumber: 5.3,
    question: '과거',
    options: ['bugun', 'manzara', 'sayohat', 'o\'tmish'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 36,
    unitNumber: 5.3,
    question: '첫사랑',
    options: ['birinchi sevgi', 'yoqmoq', 'sevmoq', 'yaxshi'],
    correctOptionIndex: 0,
  ),
];
