import 'package:get_topik_korean_quiz/models/quiz.module.dart';

List<QuizTest> book2QuizData = [
  // #1.1 Unit
  QuizTest(
    id: 1,
    unitNumber: 1.1,
    question: '교통수단',
    options: [
      'yo\'lni kesib o\'tmoq',
      'transport vositalari',
      'aeraport',
      'avtobus bekati'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 2,
    unitNumber: 1.1,
    question: '버스',
    options: [
      'avtobus bekati',
      'metro poyezd',
      'avtobus',
      'taksi',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 3,
    unitNumber: 1.1,
    question: '버스 정류장',
    options: [
      'metro bekat',
      'avtobus bekati',
      'tezyurar avtobus',
      'poyezd vokzal',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 4,
    unitNumber: 1.1,
    question: '고속버스',
    options: [
      'tezyurar avtobus',
      'mashina',
      'tak',
      'internet',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 1.1,
    question: '버스 터미널',
    options: [
      'avtobus',
      'avto vokzal',
      'aeraport',
      'chat',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 6,
    unitNumber: 1.1,
    question: '지하철',
    options: ['avtobus bekati', 'metro poyezd', 'poyezd', 'samolyot'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 7,
    unitNumber: 1.1,
    question: '지하절역',
    options: [
      'poyezd vokzal',
      'metro bekat',
      'mashina',
      'kema',
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 8,
    unitNumber: 1.1,
    question: '기차',
    options: [
      'poyezd',
      'poyezd vokzal',
      'metro',
      'aeraport',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 1.1,
    question: '기차역',
    options: ['avto vokzal', 'aeraport', 'poyezd vokzal', 'samolyot'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 10,
    unitNumber: 1.1,
    question: '비행기',
    options: ['samolyot', 'kema', 'taksi', 'mototsikl'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 1.1,
    question: '공항',
    options: ['aeraport', 'poyezd vokzal', 'internet', 'yo\'lni kesib o\'tmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 1.1,
    question: '자동차',
    options: ['mashina', 'taksi', 'mototsikl', 'metro poezd'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 1.1,
    question: '택시',
    options: ['mashina', 'samalyot', 'taksi', 'avtobus bekati'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 14,
    unitNumber: 1.1,
    question: '배(유람선)',
    options: ['kema', 'mototsikl', 'poezd', 'aeraport'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 1.1,
    question: '오토바이',
    options: ['taksi', 'mototsikl', 'kema', 'yo\'lni kesib o\'tmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 16,
    unitNumber: 1.1,
    question: '이동 동사',
    options: [
      'harakat fe`llari',
      'metro poezd',
      'aeraport',
      'yo\'lni kesib o\'tmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 1.1,
    question: '길을 건너다',
    options: ['yo\'lni kesib o\'tmoq', 'poezd', 'metro poezd', 'aeraport'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 1.1,
    question: '을/를 타다',
    options: [
      'yo\'lni kesib o\'tmoq',
      'poezd vokzal',
      '...ga minmoq/chiqmoq',
      'uzoq bekat'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 19,
    unitNumber: 1.1,
    question: '에서 내리다',
    options: [
      'yo\'lni kesib o\'tmoq',
      '...dan tushmoq',
      'metro poezd',
      'yo\'lni kesib o\'tmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 20,
    unitNumber: 1.1,
    question: '(으)로 갈아타다=환승하다',
    options: [
      'biror bekatg/joy...ga persatka qilmoq',
      'mashina',
      'yo\'lni kesib o\'tmoq',
      'poezd vokzal'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 1.1,
    question: '에서 출발하다',
    options: ['...dan jo\'nab ketmoq', 'aeraport', 'poezd', 'metro poezd'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 1.1,
    question: '에 도착하다',
    options: [
      'yo\'lni kesib o\'tmoq',
      'metro poezd',
      '...ga yetib bormoq',
      'samalyot'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 23,
    unitNumber: 1.1,
    question: '숟가락',
    options: ['cho\'p qoshiq', 'qoshiq', 'chat', 'yo\'lni kesib o\'tmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 24,
    unitNumber: 1.1,
    question: '젓가락',
    options: ['chat', 'cho\'p qoshiq', 'qoshiq', 'yo\'lni kesib o\'tmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 25,
    unitNumber: 1.1,
    question: '인터넷',
    options: ['chat', 'aeraport', 'qoshiq', 'internet'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 26,
    unitNumber: 1.1,
    question: '채팅',
    options: ['qoshiq', 'chat', 'poezd', 'internet'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 27,
    unitNumber: 1.1,
    question: '연락하다',
    options: [
      'avtobus bekati',
      'yo\'lni kesib o\'tmoq',
      'aloqalashmoq/bog\'lanmoq',
      'aeraport'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 28,
    unitNumber: 1.1,
    question: '대학로',
    options: ['dehangno\'(joy nomi)', 'metro poezd', 'aeraport', 'qoshiq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 1.1,
    question: '경북궁',
    options: [
      'poezd',
      'kyongbukkung(joy nomi)',
      'qoshiq',
      'yo\'lni kesib o\'tmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 30,
    unitNumber: 1.1,
    question: '먼저',
    options: ['avtobus', 'avvalo/birinchi', 'yo\'lni kesib o\'tmoq', 'poezd'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 31,
    unitNumber: 1.1,
    question: '시간',
    options: ['qoshiq', 'vaqt', 'ikkisi', 'yo\'lni kesib o\'tmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 32,
    unitNumber: 1.1,
    question: '(두)달',
    options: ['bir kun', 'ikki oy', 'uch kun', 'besh kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 33,
    unitNumber: 1.1,
    question: '(이)개월',
    options: ['ikki oy', 'olti kun', 'yo\'lni kesib o\'tmoq', 'ikki hafta'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 1.1,
    question: '(이)주',
    options: ['ikki kun', 'ikki hafta', 'yo\'lni kesib o\'tmoq', 'ikki soat'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 35,
    unitNumber: 1.1,
    question: '(이)주일',
    options: ['ikki hafta', 'ikki kun', 'olti kun', 'besh kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 36,
    unitNumber: 1.1,
    question: '일',
    options: ['bir kun', 'kun', 'ikki oy', 'ikki soat'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 37,
    unitNumber: 1.1,
    question: '하루',
    options: ['ikkisi', 'bir kun', 'ikki hafta', 'olti kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 38,
    unitNumber: 1.1,
    question: '이틀',
    options: ['ikki kun', 'ikki hafta', 'uch kun', 'to\'rt kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 39,
    unitNumber: 1.1,
    question: '사흘',
    options: ['ikki oy', 'uch kun', 'besh kun', 'o\'n kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 40,
    unitNumber: 1.1,
    question: '나흘',
    options: ['ikki soat', 'besh kun', 'to\'rt kun', 'yetti kun'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 41,
    unitNumber: 1.1,
    question: '닷새',
    options: ['besh kun', 'ikki kun', 'olti kun', 'sakkiz kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 42,
    unitNumber: 1.1,
    question: '엿새',
    options: ['o\'n ikki kun', 'olti kun', 'to\'qqiz kun', 'ikki kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 43,
    unitNumber: 1.1,
    question: '이레',
    options: ['ikki oy', 'ikki hafta', 'yetti kun', 'ikkisi'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 44,
    unitNumber: 1.1,
    question: '여드레',
    options: ['yetti kun', 'olti kun', 'sakkiz kun', 'besh kun'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 45,
    unitNumber: 1.1,
    question: '아흐레',
    options: ['ikki hafta', 'to\'qqiz kun', 'o\'n kun', 'ikkisi'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 46,
    unitNumber: 1.1,
    question: '열흘',
    options: ['to\'qqiz kun', 'o\'n kun', 'bir kun', 'ikki oy'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 47,
    unitNumber: 1.1,
    question: '열하루',
    options: ['ikki soat', 'o\'n bir kun', 'ikki hafta', 'uch kun'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 48,
    unitNumber: 1.1,
    question: '열이틀',
    options: ['o\'n ikki kun', 'ikki oy', 'olti kun', 'yetti kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 49,
    unitNumber: 1.1,
    question: '(두)시간',
    options: ['ikki soat', 'ikki kun', 'olti kun', 'to\'rt kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 50,
    unitNumber: 1.1,
    question: '(이)분',
    options: ['ikki kun', 'ikki soat', 'ikki daqiqa', 'ikki hafta'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 51,
    unitNumber: 1.1,
    question: '얼마나',
    options: ['qoshiq', 'kun', 'qancha vaqt', 'ikki oy'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 52,
    unitNumber: 1.1,
    question: '명사+만',
    options: ['ot + faqat', 'chat', 'qoshiq', 'kun'],
    correctOptionIndex: 0,
  ),

  // #1.2 Unit
  QuizTest(
    id: 1,
    unitNumber: 1.2,
    question: '버스/지하철 관련 명사',
    options: [
      'transport kartasi',
      'avtobus/metroga oid otlar',
      'minish joyi',
      'tushish joyi'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 2,
    unitNumber: 1.2,
    question: '교통가드',
    options: [
      'kilib borish joyi(yo\'lagi)',
      'yo\'l tirband bo\'lmoq',
      'transport kartasi',
      'almasish(persatka) joyi(yo\'lagi)'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 3,
    unitNumber: 1.2,
    question: '요금',
    options: ['ijaraga olmoq', 'to\'lov', 'vaqt', 'tirband'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 4,
    unitNumber: 1.2,
    question: '타는 곳',
    options: [
      'minish joyi',
      'kirib borish joyi(yo\'lagi)',
      'tushish joyi',
      'zina orqali kelmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 1.2,
    question: '내리는 곳',
    options: [
      'almasish(persatka) joyi(yo\'lagi)',
      'minish joyi',
      'tushish joyi',
      'dam olish vaqti (tanaffus)'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 6,
    unitNumber: 1.2,
    question: '들어가는 곳',
    options: [
      'kirib borish joyi(yo\'lagi)',
      'minish joyi',
      'yo\'l tirband bo\'lmoq',
      'zina orqali ketmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 1.2,
    question: '갈아타는 곳',
    options: [
      'avtobus/metroga oid otlar',
      'almashish(persatka) joyi(yo\'lagi)',
      'dam olish vaqti (tanaffus)',
      'yo\'l tirband bo\'lmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 8,
    unitNumber: 1.2,
    question: '이동 동사',
    options: [
      '... bo\'lmoq',
      'transport kartasi',
      'yo\'l tirband bo\'lmoq',
      'harakat fe`llari'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 9,
    unitNumber: 1.2,
    question: '(방)에서 나가다',
    options: [
      '(zina)orqali tushib kelmoq',
      '(xona)dan chiqib kelmoq',
      '(xona)dan chiqib ketmoq',
      'yo\'l tirband bo\'lmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 10,
    unitNumber: 1.2,
    question: '(방)에서 나오다',
    options: [
      '(xona)dan chiqib kelmoq',
      '(zina)orqali tushib kelmoq',
      '(xona)ga kirib ketmoq',
      'dam olish vaqti (tanaffus)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 1.2,
    question: '(방)에 들어가다',
    options: [
      '(xona)dan chiqib ketmoq',
      'dam olish vaqti (tanaffus)',
      '(xona)ga kirib ketmoq',
      '(xona)dan chiqib kelmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 12,
    unitNumber: 1.2,
    question: '(방)에 들어오다',
    options: [
      '(xona)ga kirib kelmoq',
      '(xona)dan chiqib ketmoq',
      '(zina)orqali tushib ketmoq',
      'yo\'l tirband bo\'lmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 1.2,
    question: '(계단)으로 올라가다',
    options: [
      '(xona)dan chiqib ketmoq',
      '(zina)orqali tushib kelmoq',
      '(zina)orqali ko\'tarilib ketmoq',
      '(zina)orqali tushib ketmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 14,
    unitNumber: 1.2,
    question: '(계단)으로 올라오다',
    options: [
      '(zina)orqali ko\'tarilib kelmoq',
      '(xona)dan chiqib ketmoq',
      '(zina)orqali tushib ketmoq',
      'transport kartasi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 1.2,
    question: '(계단)으로 내려가다',
    options: [
      '(zina)orqali tushib ketmoq',
      '(zina)orqali tushib kelmoq',
      'yo\'l tirband bo\'lmoq',
      'dam olish vaqti (tanaffus)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 1.2,
    question: '(계단)으로 내려오다',
    options: [
      '(zina)orqali tushib kelmoq',
      '(zina)orqali tushib ketmoq',
      '(zina)orqali ko\'tarilib kelmoq',
      'yo\'l tirband bo\'lmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 1.2,
    question: '쉬는 시간',
    options: [
      'uchrashuv vaqti',
      'tirband',
      'dam olish vaqti (tanaffus)',
      'aeraport'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 18,
    unitNumber: 1.2,
    question: '병원',
    options: ['shifoxona', 'barvaqt', 'yo\'l tirband bo\'lmoq', 'qoshiq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 1.2,
    question: '살을 빼다',
    options: ['do\'stlashmoq', 'ijaraga olmoq', 'vazn tashlamoq', 'tirband'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 20,
    unitNumber: 1.2,
    question: '더럽다',
    options: ['kir', 'ijaraga olmoq', 'uchrashuv vaqti', 'aeraport'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 1.2,
    question: '시험에 합격하다',
    options: [
      'uchrashuv vaqti',
      'imtihondan o\'tmoq',
      'ijaraga olmoq',
      'shifoxona'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 22,
    unitNumber: 1.2,
    question: '빌리다',
    options: [
      'yo\'l tirband bo\'lmoq',
      'ijaraga olmoq',
      'imtihondan o\'tmoq',
      'vaqt'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 23,
    unitNumber: 1.2,
    question: '일찍',
    options: ['barvaqt', 'soat', 'vaqt', 'imtihondan o\'tmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 1.2,
    question: '사귀다',
    options: [
      'yo\'l tirband bo\'lmoq',
      'tirband',
      'do\'stlashmoq',
      'shifoxona'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 25,
    unitNumber: 1.2,
    question: '명사+이/가 되다',
    options: ['shifoxona', 'ijaraga olmoq', 'uchrashuv vaqti', '... bo\'lmoq'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 26,
    unitNumber: 1.2,
    question: '노래를 부르다',
    options: [
      'yo\'l tirband bo\'lmoq',
      'qo`shiq kuylamoq',
      'vazn tashlamoq',
      'ijaraga olmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 27,
    unitNumber: 1.2,
    question: '우산을 쓰다',
    options: [
      'yo\'l tirband bo\'lmoq',
      'soat',
      'soyabon tutmoq',
      'uchrashuv vaqti'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 28,
    unitNumber: 1.2,
    question: '길이 막히다',
    options: [
      'yo\'l tirband bo\'lmoq',
      'minish joyi',
      'zinali kelmoq',
      'vazn tashlamoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 1.2,
    question: '약속 시간',
    options: [
      'dam olish vaqti (tanaffus)',
      'uchrashuv vaqti',
      'yo\'l tirband bo\'lmoq',
      'ijaraga olmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 30,
    unitNumber: 1.2,
    question: '너무',
    options: [
      '... bo\'lmoq',
      'ijaraga olmoq',
      'juda (salbiy)',
      'vazn tashlamoq',
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 31,
    unitNumber: 1.2,
    question: '몇 번',
    options: [
      'nechanchi',
      'barvaqt',
      'ijaraga olmoq',
      'vaqt',
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 1.2,
    question: '놀이공원',
    options: [
      'vazn tashlamoq',
      'uchrashuv vaqti',
      'shifoxona',
      'istirohat bog\'i',
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 33,
    unitNumber: 1.2,
    question: '복잡하다',
    options: [
      'tirband',
      'barvaqt',
      'uchrashuv vaqti',
      'yo\'l tirband bo\'lmoq',
    ],
    correctOptionIndex: 0,
  ),

  // #1.3 Unit

  QuizTest(
    id: 1,
    unitNumber: 1.3,
    question: '교통 관련 어휘',
    options: [
      'transportga oid so\'zlar',
      'chorraha',
      'osma ko\'prik',
      'yer osti yo\'li',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 2,
    unitNumber: 1.3,
    question: '사거리',
    options: [
      'zebra',
      'svetafor',
      'chorraha',
      'to\'g\'riga bormoq',
    ],
    correctOptionIndex: 2,
  ),

  QuizTest(
    id: 3,
    unitNumber: 1.3,
    question: '육교',
    options: [
      'osma ko\'prik',
      'yer osti yo\'li',
      'o\'ngga qayrilmoq',
      'chapga qayrilmoq',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 4,
    unitNumber: 1.3,
    question: '지하도',
    options: [
      'aylanib olmoq',
      '(mashina) to\'xtamoq',
      '(mashina)ni to\'xtatmoq',
      'yer osti yo\'li',
    ],
    correctOptionIndex: 3,
  ),

  QuizTest(
    id: 5,
    unitNumber: 1.3,
    question: '횡단보도',
    options: [
      'fe\'l/sifat',
      'yashamoq',
      'zebra',
      'ochmoq',
    ],
    correctOptionIndex: 2,
  ),

  QuizTest(
    id: 6,
    unitNumber: 1.3,
    question: '신호등',
    options: ['svetafor', 'tayyorlamoq', 'sotmoq', 'yig\'lamoq'],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 7,
    unitNumber: 1.3,
    question: ' 똑바로 가다',
    options: ['uzoq', 'to\'g\'riga bormoq', 'g\'amgin', 'kulmoq'],
    correctOptionIndex: 1,
  ),

  QuizTest(
    id: 8,
    unitNumber: 1.3,
    question: '오른쪽으로 가다',
    options: ['o\'ngga qayrilmoq', 'yuk', 'haydovchi', 'oshib o\'tmoq'],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 9,
    unitNumber: 1.3,
    question: '왼쪽으로 가다',
    options: [
      'tezda',
      'boshlamoq',
      'tez',
      'chapga qayrilmoq',
    ],
    correctOptionIndex: 3,
  ),

  QuizTest(
    id: 10,
    unitNumber: 1.3,
    question: '유턴하다',
    options: ['aylanib olmoq', 'chorraha', 'osma ko\'prik', 'yer osti yo\'li'],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 11,
    unitNumber: 1.3,
    question: '(차)이/가 서다',
    options: ['qiyn', '(mashina) to\'xtamoq', 'uzun', 'uzoq'],
    correctOptionIndex: 1,
  ),

  QuizTest(
    id: 12,
    unitNumber: 1.3,
    question: '(차) 을/를 세우da',
    options: ['(mashina)ni to\'xtatmoq', 'g\'amgin', 'kulmoq', 'yuk'],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 13,
    unitNumber: 1.3,
    question: '동사/형용사',
    options: [
      'transportga oid so\'zlar',
      'chorraha',
      'fe\'l/sifat',
      'osma ko\'prik',
    ],
    correctOptionIndex: 2,
  ),

  QuizTest(
    id: 14,
    unitNumber: 1.3,
    question: '살da',
    options: [
      'yer osti yo\'li',
      'yashamoq',
      'zebra',
      'svetafor',
    ],
    correctOptionIndex: 1,
  ),

  QuizTest(
    id: 15,
    unitNumber: 1.3,
    question: '열da',
    options: [
      'ochmoq',
      'to\'g\'riga bormoq',
      'o\'ngga qayrilmoq',
      'chapga qayrilmoq',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 16,
    unitNumber: 1.3,
    question: '만들da',
    options: [
      'aylanib olmoq',
      '(mashina) to\'xtamoq',
      '(mashina)ni to\'xtatmoq',
      'tayyorlamoq',
    ],
    correctOptionIndex: 3,
  ),

  QuizTest(
    id: 17,
    unitNumber: 1.3,
    question: '팔다',
    options: [
      'sotmoq',
      'fe\'l/sifat',
      'yashamoq',
      'ochmoq',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 18,
    unitNumber: 1.3,
    question: '울da',
    options: [
      'tayyorlamoq',
      'sotmoq',
      'yig\'lamoq',
      'tezda',
    ],
    correctOptionIndex: 2,
  ),

  QuizTest(
    id: 19,
    unitNumber: 1.3,
    question: '힘들da',
    options: [
      'qiyin',
      'bos\'lanmoq',
      'tez',
      'haydovchi',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 20,
    unitNumber: 1.3,
    question: '길da',
    options: [
      'oshi bo\'tmoq',
      'uzun',
      'yuk',
      'kulmoq',
    ],
    correctOptionIndex: 1,
  ),

  QuizTest(
    id: 21,
    unitNumber: 1.3,
    question: '멀da',
    options: [
      'qiyin',
      'uzun',
      'uzoq',
      'g\'amgin',
    ],
    correctOptionIndex: 2,
  ),

  QuizTest(
    id: 22,
    unitNumber: 1.3,
    question: '슬프da',
    options: [
      'g\'amgin',
      'tezda',
      'bos\'lanmoq',
      'tez',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 23,
    unitNumber: 1.3,
    question: '웃da',
    options: [
      'qiyin',
      'uzun',
      'uzoq',
      'kulmoq',
    ],
    correctOptionIndex: 3,
  ),

  QuizTest(
    id: 24,
    unitNumber: 1.3,
    question: '짐',
    options: [
      'yuk',
      'g\'amgin',
      'oshi bo\'tmoq',
      'kulmoq',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 25,
    unitNumber: 1.3,
    question: '기사',
    options: [
      'fe\'l/sifat',
      'yashamoq',
      'ochmoq',
      'haydovchi',
    ],
    correctOptionIndex: 3,
  ),

  QuizTest(
    id: 26,
    unitNumber: 1.3,
    question: '지하도',
    options: [
      'yer osti yo\'li',
      'aylanib olmoq',
      'to\'g\'riga bormoq'
          'chorraha',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 27,
    unitNumber: 1.3,
    question: '횡단보도',
    options: ['zebra', 'fe\'l/sifat', 'yashamoq', 'ochmoq'],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 28,
    unitNumber: 1.3,
    question: '시작되다',
    options: [
      'tugamoq',
      'boshlanmoq',
      'tez',
      'yuk',
    ],
    correctOptionIndex: 0,
  ),

  QuizTest(
    id: 29,
    unitNumber: 1.3,
    question: '빨리',
    options: [
      'yuk',
      'uzun',
      'tez',
      'g\'amgin',
    ],
    correctOptionIndex: 2,
  ),

  // #2.1 Unit

  QuizTest(
    id: 1,
    unitNumber: 2.1,
    question: '복잡하다',
    options: [
      'tirband',
      'barvaqt',
      'uchrashuv',
      'yoltirb',
    ],
    correctOptionIndex: 0,
  ),

  // #2.2 Unit
QuizTest(
  id: 1,
  unitNumber: 2.2,
  question: '주거 관련 어휘',
  options: ['turar joyga oid so`zlar', 'ovqat', 'kiyim', 'kitob'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 2,
  unitNumber: 2.2,
  question: '집',
  options: ['uy', 'mashina', 'ko`cha', 'daraxt'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 3,
  unitNumber: 2.2,
  question: '아파트',
  options: ['ko`p qavatli uy', 'hovli', 'do`kon', 'bog`'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 4,
  unitNumber: 2.2,
  question: '하숙집',
  options: ['hovli', 'ko`p qavatli uy', 'do`kon', 'bog`'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 5,
  unitNumber: 2.2,
  question: '기숙사',
  options: ['yotoqxona', 'bog`', 'ko`p qavatli uy', 'do`kon'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 6,
  unitNumber: 2.2,
  question: '금지 관련 어휘',
  options: ['taqiqqa oid so`zlar', 'uy', 'bog`', 'kiyim'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 7,
  unitNumber: 2.2,
  question: '담배를 피우다',
  options: ['tamaki chekmoq', 'tuzatmoq', 'yuvmoq', 'yotmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 8,
  unitNumber: 2.2,
  question: '술을 마시다',
  options: ['aroq ichmoq', 'suv ichmoq', 'yutmoq', 'safarga chiqmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 9,
  unitNumber: 2.2,
  question: '큰소리로 떠들다',
  options: ['shovqin solmoq', 'jim turmoq', 'ovozini pasaytirmoq', 'kitob o`qimoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 10,
  unitNumber: 2.2,
  question: '수업에 늦다=지각하다',
  options: ['darsga kech qolmoq', 'darsga vaqtida bormoq', 'darsga bormaslik', 'darsni qoldirmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 11,
  unitNumber: 2.2,
  question: '쓰레기를 버리다',
  options: ['axlat tashlamoq', 'axlat yig`moq', 'axlatni olib chiqmoq', 'axlatni saralamoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 12,
  unitNumber: 2.2,
  question: '사진을 찍다',
  options: ['rasmga olmoq', 'rasm chizmoq', 'rasm sotib olmoq', 'rasm ko`rmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 13,
  unitNumber: 2.2,
  question: '반대 어휘',
  options: ['antonim so`zlar', 'sinonim so`zlar', 'mustaqil so`zlar', 'qarindosh so`zlar'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 14,
  unitNumber: 2.2,
  question: '켜다',
  options: ['yoqmoq', 'o`chirmoq', 'ochmoq', 'yopmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 15,
  unitNumber: 2.2,
  question: '끄다',
  options: ['o`chirmoq', 'yoqmoq', 'ochmoq', 'yopmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 16,
  unitNumber: 2.2,
  question: '열다',
  options: ['ochmoq', 'yopmoq', 'yoqmoq', 'o`chirmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 17,
  unitNumber: 2.2,
  question: '닫다',
  options: ['yopmoq', 'ochmoq', 'yoqmoq', 'o`chirmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 18,
  unitNumber: 2.2,
  question: '가깝다',
  options: ['yaqin', 'uzoqlik', 'kichik', 'katta'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 19,
  unitNumber: 2.2,
  question: '멀다',
  options: ['uzoqlik', 'yaqin', 'kichik', 'katta'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 20,
  unitNumber: 2.2,
  question: '편리하다',
  options: ['qulay', 'noqulay', 'yaqin', 'uzoqlik'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 21,
  unitNumber: 2.2,
  question: '불편하다',
  options: ['noqulay', 'qulay', 'yaqin', 'uzoqlik'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 22,
  unitNumber: 2.2,
  question: '잠깐',
  options: ['bir daqiqa', 'ko`p vaqt', 'tezda', 'asta-sekin'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 23,
  unitNumber: 2.2,
  question: '즐겁다',
  options: ['zavqli', 'zerikarli', 'og`ir', 'yengil'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 24,
  unitNumber: 2.2,
  question: '몸',
  options: ['tana', 'oyoq', 'bosh', 'qo`l'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 25,
  unitNumber: 2.2,
  question: '건물',
  options: ['bino', 'ko`cha', 'uy', 'bog`'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 26,
  unitNumber: 2.2,
  question: '또',
  options: ['yana', 'avval', 'keyin', 'hali'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 27,
  unitNumber: 2.2,
  question: '시설',
  options: ['jihoz', 'oshxona', 'uy', 'bog`'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 28,
  unitNumber: 2.2,
  question: '직접',
  options: ['bevosita', 'bilvosita', 'o`zi', 'boshqalar'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 29,
  unitNumber: 2.2,
  question: '주의하다',
  options: ['e`tibor bermoq', 'unutmoq', 'eslamoq', 'yozmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 30,
  unitNumber: 2.2,
  question: '많은 사람들',
  options: ['ko`p odamlar', 'kam odamlar', 'boshqa odamlar', 'begona odamlar'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 31,
  unitNumber: 2.2,
  question: '필요하다',
  options: ['kerak/zarur', 'keraksiz', 'o`rtacha', 'mahsus'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 32,
  unitNumber: 2.2,
  question: '인터넷을 사용하다/쓰다',
  options: ['internetdan foydalanmoq', 'internet sotib olmoq', 'internet yozmoq', 'internetni qidirish'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 33,
  unitNumber: 2.2,
  question: '세탁기를 사용하다/쓰다',
  options: ['kir yuvish mashinasini ishlatmoq', 'kir yuvmoq', 'mashina sotib olmoq', 'uy yig`ishtirmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 34,
  unitNumber: 2.2,
  question: '외국인',
  options: ['chet ellik', 'o`zbek', 'qo`shni', 'hamkasb'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 35,
  unitNumber: 2.2,
  question: '하숙비',
  options: ['ijara to`lovi', 'elektr to`lovi', 'suv to`lovi', 'gaz to`lovi'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 36,
  unitNumber: 2.2,
  question: '생활 규칙',
  options: ['hayot qoidasi', 'o`quv qoidasi', 'uy qoidasi', 'ko`cha qoidasi'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 37,
  unitNumber: 2.2,
  question: '지키다',
  options: ['amal qilmoq', 'buzmoq', 'unutmoq', 'yozmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 38,
  unitNumber: 2.2,
  question: '부엌',
  options: ['oshxona', 'yotoqxona', 'hammom', 'mehmonxona'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 39,
  unitNumber: 2.2,
  question: '쓰레기통',
  options: ['axlat quti', 'kitob javoni', 'stol', 'kreslo'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 40,
  unitNumber: 2.2,
  question: '전기',
  options: ['elektr', 'gaz', 'suv', 'yorug`lik'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 41,
  unitNumber: 2.2,
  question: '아껴 쓰다',
  options: ['tejab ishlatmoq', 'sarflamoq', 'isrof qilmoq', 'yig`ishtirmoq'],
  correctOptionIndex: 0,
),

  // #2.3 Unit

  QuizTest(
  id: 1,
  unitNumber: 2.3,
  question: '전화 관련 동사',
  options: ['qo`ng`iroqqa oid fe`llar', 'poyafzal', 'qovurmoq', 'ovqat'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 2,
  unitNumber: 2.3,
  question: '전화를 하다=걸다',
  options: ['qo`ng`iroq qilmoq', 'sms yubormoq', 'yuvmoq', 'tozalamoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 3,
  unitNumber: 2.3,
  question: '전화가 오다',
  options: ['qo`ng`iroq kelmoq', 'sms kelmoq', 'go`shakni qo`ymoq', 'kitob o`qimoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 4,
  unitNumber: 2.3,
  question: '전화를 받다',
  options: ['go`shakni ko`tarmoq', 'qong`iroq qilmoq', 'sotib olmoq', 'tezda bormoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 5,
  unitNumber: 2.3,
  question: '문자를 보내다',
  options: ['sms yubormoq', 'sms o`qimoq', 'sms o`chirmoq', 'sms topmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 6,
  unitNumber: 2.3,
  question: '문자를 받다',
  options: ['sms olmoq', 'sms yozmoq', 'sms yubormoq', 'sms ko`rmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 7,
  unitNumber: 2.3,
  question: '문자를 지우다',
  options: ['smsni o`chirmoq', 'sms yubormoq', 'sms olmoq', 'sms topmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 8,
  unitNumber: 2.3,
  question: '통화하다',
  options: ['telefonda gaplashmoq', 'qong`iroq qilmoq', 'sms yubormoq', 'sms olmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 9,
  unitNumber: 2.3,
  question: '전화를 잘못 걸다',
  options: ['raqamni noto`g`ri terib qo`ng`iroq qilmoq', 'qo`ng`iroq qilmoq', 'qo`ng`iroq tugatmoq', 'telefonni almashtirmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 10,
  unitNumber: 2.3,
  question: '전화를 바꿔 주다',
  options: ['qo`ng`iroqni o`zgartirmoq', 'qo`ng`iroq qilmoq', 'qo`ng`iroq tugatmoq', 'qo`ng`iroq kelmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 11,
  unitNumber: 2.3,
  question: '전화를 끊다',
  options: ['qo`ng`iroqni tugatmoq', 'qo`ng`iroq qilmoq', 'qo`ng`iroq kelmoq', 'qo`ng`iroq o`zgartirmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 12,
  unitNumber: 2.3,
  question: '누구세요?',
  options: ['kimsiz?', 'nimadir', 'nimasiz?', 'sizmisiz?'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 13,
  unitNumber: 2.3,
  question: '여보세요',
  options: ['alo', 'salom', 'xayr', 'ha'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 14,
  unitNumber: 2.3,
  question: '잠깐만요',
  options: ['bir daqiqa', 'hozir', 'kechikib kelmoq', 'tezda'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 15,
  unitNumber: 2.3,
  question: '접속사',
  options: ['bog`lovchi', 'poyafzal', 'kitob', 'do`kon'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 16,
  unitNumber: 2.3,
  question: '그리고',
  options: ['va, so`ng', 'lekin', 'agar', 'to`g`ri'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 17,
  unitNumber: 2.3,
  question: '그래서',
  options: ['shuning uchun', 'u uchun', 'buning uchun', 'nimaga'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 18,
  unitNumber: 2.3,
  question: '그러면=그럼',
  options: ['unday bo`lsa, u holda, unda', 'boshqa', 'albatta', 'vaqtincha'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 19,
  unitNumber: 2.3,
  question: '그런데',
  options: ['lekin, aytgancha', 'shuning uchun', 'va', 'balki'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 20,
  unitNumber: 2.3,
  question: '피아노를 치다',
  options: ['pionino chalmoq', 'gitara chalmoq', 'pionino o`rganmoq', 'musiqa chalmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 21,
  unitNumber: 2.3,
  question: '매운 음식',
  options: ['achchiq ovqat', 'shirin ovqat', 'sho`r ovqat', 'mazali ovqat'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 22,
  unitNumber: 2.3,
  question: '좋은 점수를 받다',
  options: ['yaxshi baho olmoq', 'yomon baho olmoq', 'o`rtacha baho olmoq', 'bahosiz qolmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 23,
  unitNumber: 2.3,
  question: '테니스를 치다',
  options: ['tennis o`ynamoq', 'shaxmat o`ynamoq', 'mashq qilmoq', 'yugurmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 24,
  unitNumber: 2.3,
  question: '운전을 하다',
  options: ['mashina haydamoq', 'poyezd haydamoq', 'samolyot uchirmoq', 'velosiped haydamoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 25,
  unitNumber: 2.3,
  question: '준비하다',
  options: ['tayyorlamoq/tayyorlanmoq', 'boshlamoq', 'bitirmoq', 'tugallamoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 26,
  unitNumber: 2.3,
  question: '다른 날',
  options: ['boshqa kun', 'shu kun', 'keyingi kun', 'o`tgan kun'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 27,
  unitNumber: 2.3,
  question: '바꾸다',
  options: ['o`zgartirmoq /almashtirmoq', 'o`ylamoq', 'tanlamoq', 'boshlamoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 28,
  unitNumber: 2.3,
  question: '혹시',
  options: ['mabodo', 'agar', 'bo`lsa', 'yo`q'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 29,
  unitNumber: 2.3,
  question: '명사+말고',
  options: ['ot+o`rniga', 'ot+uchun', 'ot+oldin', 'ot+keyin'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 30,
  unitNumber: 2.3,
  question: '아직',
  options: ['hali', 'hozir', 'avval', 'kech'],
  correctOptionIndex: 0,
),

  // #3.1 Unit

 QuizTest(
  id: 1,
  unitNumber: 3.1,
  question: '탈착 동사',
  options: ['kiyinish fe`llar', 'ovqat fe`llar', 'sayohat fe`llar', 'ish fe`llar'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 2,
  unitNumber: 3.1,
  question: '쓰다',
  options: ['kiymoq/taqmoq(ko`zoynak)', 'o`qimoq', 'yozmoq', 'ichmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 3,
  unitNumber: 3.1,
  question: '입다',
  options: ['kiymoq(shim/ko`ylak)', 'o`rganmoq', 'uchmoq', 'yugurmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 4,
  unitNumber: 3.1,
  question: '신다',
  options: ['kiymoq(oyoq kiyim)', 'yozmoq', 'chizmoq', 'kuymoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 5,
  unitNumber: 3.1,
  question: '벗다',
  options: ['yechmoq', 'kiymoq', 'yemoq', 'ichmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 6,
  unitNumber: 3.1,
  question: '차다',
  options: ['taqmoq(qo`l soat)', 'o`ynamoq', 'yurmoq', 'sotmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 7,
  unitNumber: 3.1,
  question: '매다',
  options: ['taqmoq(galstuk)', 'ushlab turmoq', 'boshlamoq', 'o`chmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 8,
  unitNumber: 3.1,
  question: '풀다',
  options: ['yechmoq', 'o`ramoq', 'tortmoq', 'ko`rmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 9,
  unitNumber: 3.1,
  question: '끼다',
  options: ['taqmoq(qo`lqop/uzuk)', 'tirishmoq', 'chiqmoq', 'kirmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 10,
  unitNumber: 3.1,
  question: '하다',
  options: ['taqmoq(halqa)', 'qilmoq', 'ko`tarilmoq', 'charmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 11,
  unitNumber: 3.1,
  question: '빼다',
  options: ['yechmoq', 'chiqmoq', 'yig`lamoq', 'yiqilmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 12,
  unitNumber: 3.1,
  question: '빨갛다',
  options: ['qizil', 'ko`k', 'oq', 'qora'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 13,
  unitNumber: 3.1,
  question: '노랗다',
  options: ['sariq', 'yashil', 'to`q', 'ochiq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 14,
  unitNumber: 3.1,
  question: '파랗다',
  options: ['ko`k', 'sariq', 'pushti', 'to`q sariq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 15,
  unitNumber: 3.1,
  question: '하얗다',
  options: ['oq', 'qora', 'qizil', 'ko`k'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 16,
  unitNumber: 3.1,
  question: '까맣다',
  options: ['qora', 'oq', 'yashil', 'ko`k'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 17,
  unitNumber: 3.1,
  question: '이렇다',
  options: ['bunday', 'unda', 'shunday', 'anavinday'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 18,
  unitNumber: 3.1,
  question: '그렇다',
  options: ['shunday', 'bunday', 'unda', 'anavinday'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 19,
  unitNumber: 3.1,
  question: '저렇다',
  options: ['anavinday', 'unda', 'shunday', 'bunday'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 20,
  unitNumber: 3.1,
  question: '어떻다',
  options: ['qanday', 'bunday', 'unda', 'shunday'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 21,
  unitNumber: 3.1,
  question: '양복',
  options: ['kostyum shim', 'paypoq', 'oyoq kiyim', 'ko`ylak'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 22,
  unitNumber: 3.1,
  question: '안경',
  options: ['ko`zoynak', 'soat', 'uzuk', 'qo`lqop'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 23,
  unitNumber: 3.1,
  question: '티셔츠',
  options: ['futbolka', 'uzuk', 'ko`ylak', 'ko`zoynak'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 24,
  unitNumber: 3.1,
  question: '치마',
  options: ['yubka', 'ko`ylak', 'futbolka', 'paypoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 25,
  unitNumber: 3.1,
  question: '양말',
  options: ['paypoq', 'oyoq kiyim', 'kostyum shim', 'ko`zoynak'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 26,
  unitNumber: 3.1,
  question: '넥타이',
  options: ['galstuk', 'ko`ylak', 'futbolka', 'kostyum shim'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 27,
  unitNumber: 3.1,
  question: '반지',
  options: ['uzuk', 'soat', 'zanjir', 'halqa'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 28,
  unitNumber: 3.1,
  question: '장갑',
  options: ['qo`lqop', 'futbolka', 'paypoq', 'ko`ylak'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 29,
  unitNumber: 3.1,
  question: '목걸이',
  options: ['zanjir(sepochka)', 'soat', 'ko`zoynak', 'uzuk'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 30,
  unitNumber: 3.1,
  question: '귀걸이',
  options: ['halqa', 'zanjir', 'ko`zoynak', 'soat'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 31,
  unitNumber: 3.1,
  question: '머리띠',
  options: ['abadok', 'ko`ylak', 'uzuk', 'ko`zoynak'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 32,
  unitNumber: 3.1,
  question: '색깔',
  options: ['rang', 'kiyim', 'tarz', 'bino'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 33,
  unitNumber: 3.1,
  question: '하늘',
  options: ['osmon', 'yer', 'daryo', 'tog`'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 34,
  unitNumber: 3.1,
  question: '귀엽다',
  options: ['yoqimtoy', 'jasur', 'oqil', 'kamtar'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 35,
  unitNumber: 3.1,
  question: '부끄럽다',
  options: ['uyatchan', 'tuyg`uli', 'qattiqqo`l', 'kulgili'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 36,
  unitNumber: 3.1,
  question: '피부',
  options: ['teri', 'soch', 'tirnoq', 'ko`z'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 37,
  unitNumber: 3.1,
  question: '구름',
  options: ['bulut', 'quyosh', 'oy', 'yulduz'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 38,
  unitNumber: 3.1,
  question: '감기',
  options: ['tumov/shamollash', 'isitma', 'oshqozon og`rig`i', 'ko`z og`rig`i'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 39,
  unitNumber: 3.1,
  question: '명사+때문에',
  options: ['ot+ sababli', 'ot+ ustida', 'ot+ tufayli', 'ot+ bilan'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 40,
  unitNumber: 3.1,
  question: '열이 나다',
  options: ['isitmalamoq', 'titrash', 'qaltiramoq', 'qizilmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 41,
  unitNumber: 3.1,
  question: '눈이 내리다',
  options: ['qor yog`moq', 'yomg`ir yog`moq', 'shamol esmoq', 'yashin chaqmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 42,
  unitNumber: 3.1,
  question: '수박',
  options: ['tarvuz', 'qovun', 'olma', 'shaftoli'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 43,
  unitNumber: 3.1,
  question: '높다',
  options: ['baland', 'past', 'uzoq', 'yaqin'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 44,
  unitNumber: 3.1,
  question: '유행이다',
  options: ['urfda/mashhur', 'eski', 'noqulay', 'zamonaviy'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 45,
  unitNumber: 3.1,
  question: '스타일',
  options: ['stil/ko`rinish', 'kiyim', 'tarz', 'shahar'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 46,
  unitNumber: 3.1,
  question: '사이즈',
  options: ['o`lcham/razmer', 'uzunlik', 'bo`y', 'eni'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 47,
  unitNumber: 3.1,
  question: '문제',
  options: ['muammo', 'yechim', 'savol', 'javob'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 48,
  unitNumber: 3.1,
  question: '헬스장',
  options: ['sport zal(tosh ko`taradigan)', 'o`quv zal', 'kinozal', 'suv havzasi'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 49,
  unitNumber: 3.1,
  question: '반바지',
  options: ['shortik', 'shim', 'ko`ylak', 'yubka'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 50,
  unitNumber: 3.1,
  question: '옷가게',
  options: ['kiyim do`koni', 'kitob do`koni', 'o`yinchoq do`koni', 'mebel do`koni'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 51,
  unitNumber: 3.1,
  question: '교환하다',
  options: ['(sotib olingan kiyimni) almashtirmoq', 'olmoq', 'sotmoq', 'qo`shmoq'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 52,
  unitNumber: 3.1,
  question: '노트복',
  options: ['noutbook', 'telefon', 'kompyuter', 'planshet'],
  correctOptionIndex: 0,
),
QuizTest(
  id: 53,
  unitNumber: 3.1,
  question: '무섭다',
  options: ['qo`rqinchli', 'yoqimli', 'ajoyib', 'kulgili'],
  correctOptionIndex: 0,
),

  // #3.2 Unit

  QuizTest(
    id: 1,
    unitNumber: 3.2,
    question: '옷의 종류',
    options: ['narx', 'sabzavot', 'kiyimlarning turlari', 'qalay'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 2,
    unitNumber: 3.2,
    question: '바지',
    options: ['shim', 'jaket', 'yubka', 'paypoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 3.2,
    question: '청바지',
    options: ['yashil rang', 'suzish kiyimi', 'ayollar sumkasi', 'jinsi shim'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 4,
    unitNumber: 3.2,
    question: '치마',
    options: ['yubka', 'erkaklar ko`ylagi', 'paypoq', 'galstuk'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 3.2,
    question: '재킷',
    options: ['jaket', 'ayollar ko`ylagi', 'bluska', 'suzish kiyimi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 3.2,
    question: '와이셔츠',
    options: ['galstuk', 'erkaklar ko`ylagi', 'ayollar sumkasi', 'bluska'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 7,
    unitNumber: 3.2,
    question: '원피스',
    options: ['yubka', 'erkaklar ko`ylagi', 'ayollar ko`ylagi', 'paypoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 8,
    unitNumber: 3.2,
    question: '블라우스',
    options: ['paypoq', 'suzish kiyimi', 'bluska', 'ayollar sumkasi'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 9,
    unitNumber: 3.2,
    question: '수영복',
    options: ['suzish kiyimi', 'bluska', 'paypoq', 'galstuk'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 10,
    unitNumber: 3.2,
    question: '양말',
    options: ['paypoq', 'galstuk', 'ayollar sumkasi', 'bermoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 3.2,
    question: '넥타이',
    options: ['paypoq', 'galstuk', 'ayollar sumkasi', 'bermoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 3.2,
    question: '핸드백',
    options: ['ayollar sumkasi', 'bermoq', 'olmoq', '(shaxs)oti+ga'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 3.2,
    question: '주다/드리다',
    options: ['bermoq', 'olmoq', '(shaxs)oti+ga', '(shaxs)oti+dan'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 3.2,
    question: '받다',
    options: ['bermoq', 'olmoq', '(shaxs)oti+ga', '(shaxs)oti+dan'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 15,
    unitNumber: 3.2,
    question: '명사+에게/한테',
    options: ['olmoq', '(shaxs)oti+ga', '(shaxs)oti+dan', 'yanada/yanayam'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 16,
    unitNumber: 3.2,
    question: '명사+에게서/한테서',
    options: ['olmoq', '(shaxs)oti+ga', '(shaxs)oti+dan', 'yanada/yanayam'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 17,
    unitNumber: 3.2,
    question: '더',
    options: ['(shaxs)oti+dan', 'yanada/yanayam', 'yarashmoq', 'yashil rang'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 18,
    unitNumber: 3.2,
    question: '어울리다',
    options: ['yanada/yanayam', 'yarashmoq', 'yashil rang', 'sabzavot'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 3.2,
    question: '초록색',
    options: ['yarashmoq', 'yashil rang', 'sabzavot', 'atirgul'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 20,
    unitNumber: 3.2,
    question: '야채',
    options: ['yashil rang', 'sabzavot', 'atirgul', 'balki'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 21,
    unitNumber: 3.2,
    question: '장미꽃',
    options: ['sabzavot', 'atirgul', 'balki', 'qalbiga yoqmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 22,
    unitNumber: 3.2,
    question: '아마',
    options: ['atirgul', 'balki', 'qalbiga yoqmoq', 'qulay'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 23,
    unitNumber: 3.2,
    question: '마음에 들다',
    options: ['balki', 'qalbiga yoqmoq', 'qulay', 'narx'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 24,
    unitNumber: 3.2,
    question: '편하다',
    options: ['qalbiga yoqmoq', 'qulay', 'narx', 'kiyimlarning turlari'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 25,
    unitNumber: 3.2,
    question: '가격',
    options: ['qulay', 'narx', 'kiyimlarning turlari', 'shim'],
    correctOptionIndex: 1,
  ),

  // #3.3 Unit

  QuizTest(
    id: 1,
    unitNumber: 3.3,
    question: '돈의 종류',
    options: ['pulning turlari', '10', '100', '1000'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 3.3,
    question: '십',
    options: ['10', '1000', '10 won', '50 won'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 3.3,
    question: '백',
    options: ['1000', '100', '100 won', '50 won'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 4,
    unitNumber: 3.3,
    question: '천',
    options: ['1000', '100', '10.000 won', '500 won'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 3.3,
    question: '만',
    options: ['10', '1000', '10.000', '50.000 won'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 6,
    unitNumber: 3.3,
    question: '십원',
    options: ['10 won', '50 won', '100 won', '500 won'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 3.3,
    question: '오십 원',
    options: ['10 won', '50 won', '100 won', '500 won'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 8,
    unitNumber: 3.3,
    question: '백 원',
    options: ['100 won', '500 won', '1000 won', '5000 won'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 3.3,
    question: '오백 원',
    options: ['100 won', '500 won', '1000 won', '5000 won'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 10,
    unitNumber: 3.3,
    question: '천 원',
    options: ['1000 won', '5000 won', '10.000 won', '50.000 won'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 3.3,
    question: '오천 원',
    options: ['500 won', '5000 won', '10.000 won', '50.000 won'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 3.3,
    question: '만 원',
    options: ['1000 won', '5000 won', '10.000 won', '50.000 won'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 13,
    unitNumber: 3.3,
    question: '오만 원',
    options: ['5000 won', '10.000 won', '50.000 won', '1000 won'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 14,
    unitNumber: 3.3,
    question: '단위 명사',
    options: [
      'o`lchov birligi',
      'odam/ta=kishi',
      'narsa/ ta=dona',
      'kiyim/dona'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 3.3,
    question: '사람/명',
    options: [
      'o`lchov birligi',
      'odam/ta=kishi',
      'narsa/ ta=dona',
      'kiyim/dona'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 16,
    unitNumber: 3.3,
    question: '물건/개',
    options: [
      'odam/ta=kishi',
      'narsa/ ta=dona',
      'kiyim/dona',
      'oyoq kiyim/ ta=juft'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 17,
    unitNumber: 3.3,
    question: '옷/벌',
    options: [
      'narsa/ ta=dona',
      'kiyim/dona',
      'oyoq kiyim/ ta=juft',
      'qahva/ ta=stakan'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 18,
    unitNumber: 3.3,
    question: '신발/켤레',
    options: [
      'kiyim/dona',
      'oyoq kiyim/ ta=juft',
      'qahva/ ta=stakan',
      'suv/ ta= stakan'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 19,
    unitNumber: 3.3,
    question: '커피/잔',
    options: [
      'oyoq kiyim/ ta=juft',
      'qahva/ ta=stakan',
      'suv/ ta= stakan',
      'sharbat/ ta=butilka'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 20,
    unitNumber: 3.3,
    question: '물/컵',
    options: [
      'qahva/ ta=stakan',
      'suv/ ta= stakan',
      'sharbat/ ta=butilka',
      'fe`l'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 21,
    unitNumber: 3.3,
    question: '주스/병',
    options: [
      'suv/ ta= stakan',
      'sharbat/ ta=butilka',
      'fe`l',
      'tuzalmoq/ yaxshi'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 22,
    unitNumber: 3.3,
    question: '동사',
    options: [
      'sharbat/ ta=butilka',
      'fe`l',
      'tuzalmoq/ yaxshi',
      'shishmoq/(suv) quyish'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 23,
    unitNumber: 3.3,
    question: '낫다',
    options: [
      'fe`l',
      'tuzalmoq/ yaxshi',
      'shishmoq/(suv) quyish',
      'aralashtirmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 24,
    unitNumber: 3.3,
    question: '붓다',
    options: [
      'tuzalmoq/ yaxshi',
      'shishmoq/(suv) quyish',
      'aralashtirmoq',
      '(uy) qurmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 25,
    unitNumber: 3.3,
    question: '젓다',
    options: [
      'shishmoq/(suv) quyish',
      'aralashtirmoq',
      '(uy) qurmoq',
      'yuvmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 26,
    unitNumber: 3.3,
    question: '짓다',
    options: ['aralashtirmoq', '(uy) qurmoq', 'yuvmoq', 'kulmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 27,
    unitNumber: 3.3,
    question: '씻다',
    options: ['(uy) qurmoq', 'yuvmoq', 'kulmoq', 'sabzavot'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 28,
    unitNumber: 3.3,
    question: '웃다',
    options: ['yuvmoq', 'kulmoq', 'sabzavot', 'seoul'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 29,
    unitNumber: 3.3,
    question: '채소',
    options: ['kulmoq', 'sabzavot', 'seoul', 'busan'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 30,
    unitNumber: 3.3,
    question: '서울',
    options: ['sabzavot', 'seoul', 'busan', 'dizayn/stil'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 31,
    unitNumber: 3.3,
    question: '부산',
    options: ['seoul', 'busan', 'dizayn/stil', 'keng'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 32,
    unitNumber: 3.3,
    question: '디자인',
    options: ['busan', 'dizayn/stil', 'keng', 'past'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 33,
    unitNumber: 3.3,
    question: '넓다',
    options: ['dizayn/stil', 'keng', 'past', 'ko`ngil ko`tarilmoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 34,
    unitNumber: 3.3,
    question: '낮다',
    options: ['keng', 'past', 'ko`ngil ko`tarilmoq', 'shakar'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 35,
    unitNumber: 3.3,
    question: '신나다',
    options: ['past', 'ko`ngil ko`tarilmoq', 'shakar', 'juda'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 36,
    unitNumber: 3.3,
    question: '설탕',
    options: ['ko`ngil ko`tarilmoq', 'shakar', 'juda', 'keng/ uzoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 37,
    unitNumber: 3.3,
    question: '참',
    options: ['shakar', 'juda', 'keng/ uzoq', 'hammasi/barchasi'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 38,
    unitNumber: 3.3,
    question: '푹',
    options: ['juda', 'keng/ uzoq', 'hammasi/barchasi', 'idishli ramyon'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 39,
    unitNumber: 3.3,
    question: '다',
    options: ['keng/ uzoq', 'hammasi/barchasi', 'idishli ramyon', 'qaynoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 40,
    unitNumber: 3.3,
    question: '컵라면',
    options: ['hammasi/barchasi', 'idishli ramyon', 'qaynoq', 'toza'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 41,
    unitNumber: 3.3,
    question: '뜨겁다',
    options: ['idishli ramyon', 'qaynoq', 'toza', 'kakao'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 42,
    unitNumber: 3.3,
    question: '깨끗이',
    options: ['qaynoq', 'toza', 'kakao', 'hisoblamoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 43,
    unitNumber: 3.3,
    question: '코코아',
    options: ['toza', 'kakao', 'hisoblamoq', 'vazn tashlamoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 44,
    unitNumber: 3.3,
    question: '계산하다',
    options: ['kakao', 'hisoblamoq', 'vazn tashlamoq', 'pulning turlari'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 45,
    unitNumber: 3.3,
    question: '살이 빠지다',
    options: ['hisoblamoq', 'vazn tashlamoq', 'pulning turlari', '10'],
    correctOptionIndex: 1,
  ),

  // #4.1 Unit

  QuizTest(
    id: 1,
    unitNumber: 4.1,
    question: '병',
    options: [
      'kasallik',
      'bosh ogrigi',
      'kuchliroq bosh ogrigi',
      'tish ogrigi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 4.1,
    question: '두통',
    options: [
      'bosh ogrigi',
      'kuchliroq bosh ogrigi',
      'menstrual(ayollar kasalligi)',
      'oshqozon ogrigi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 4.1,
    question: '편두통',
    options: [
      'kuchliroq bosh ogrigi',
      'tish ogrigi',
      'menstrual(ayollar kasalligi)',
      'oshqozon ogrigi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 4.1,
    question: '치통',
    options: [
      'tish ogrigi',
      'menstrual(ayollar kasalligi)',
      'oshqozon ogrigi',
      'bogim ogrig`i'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 4.1,
    question: '생리통',
    options: [
      'menstrual(ayollar kasalligi)',
      'oshqozon ogrigi',
      'bogim ogrig`i',
      'semptom/belgi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 4.1,
    question: '복통',
    options: ['oshqozon ogrigi', 'bogim ogrig`i', 'semptom/belgi', 'isitlamoq'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 7,
    unitNumber: 4.1,
    question: '근육통',
    options: ['bogim ogrig`i', 'semptom/belgi', 'isitlamoq', 'yo`talmоq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 4.1,
    question: '증상',
    options: ['semptom/belgi', 'isitlamoq', 'yo`talmоq', 'holsizlanmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 4.1,
    question: '열이 나다',
    options: ['isitlamoq', 'yo`talmоq', 'holsizlanmoq', 'tomogi ogrimoq'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 10,
    unitNumber: 4.1,
    question: '기침을 하다',
    options: ['yo`talmоq', 'holsizlanmoq', 'tomogi ogrimoq', 'ko`chmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 4.1,
    question: '몸살이 나다',
    options: ['holsizlanmoq', 'tomogi ogrimoq', 'burni oqmoq', 'burni bitmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 4.1,
    question: '목이 아프다',
    options: ['tomogi ogrimoq', 'burni oqmoq', 'burni bitmoq', 'bilak'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 4.1,
    question: '콧물이 나다',
    options: ['burni oqmoq', 'burni bitmoq', 'bilak', 'tish'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 4.1,
    question: '코가 막히다',
    options: ['burni bitmoq', 'bilak', 'tish', 'kuchli'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 15,
    unitNumber: 4.1,
    question: '팔',
    options: ['bilak', 'tish', 'kuchli', 'bosh ogrigi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 4.1,
    question: '다리',
    options: ['tish', 'kuchli', 'bosh ogrigi', 'oyoq'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 17,
    unitNumber: 4.1,
    question: '이',
    options: ['kuchli', 'bosh ogrigi', 'oyoq', 'semptom/belgi'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 18,
    unitNumber: 4.1,
    question: '심하다',
    options: ['bosh ogrigi', 'oyoq', 'semptom/belgi', 'isitlamoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 4.1,
    question: '이사를 하다',
    options: ['oyoq', 'semptom/belgi', 'isitlamoq', 'ko`chmoq'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 20,
    unitNumber: 4.1,
    question: '감기에 걸리다',
    options: [
      'semptom/belgi',
      'isitlamoq',
      'ko`chmoq',
      'shamollashga chalinmoq'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 21,
    unitNumber: 4.1,
    question: '취소하다',
    options: [
      'isitlamoq',
      'ko`chmoq',
      'shamollashga chalinmoq',
      'bekor qilmoq'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 22,
    unitNumber: 4.1,
    question: '연습을 하다',
    options: [
      'ko`chmoq',
      'shamollashga chalinmoq',
      'bekor qilmoq',
      'mashq qilmoq'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 23,
    unitNumber: 4.1,
    question: '발음',
    options: [
      'shamollashga chalinmoq',
      'bekor qilmoq',
      'mashq qilmoq',
      'talaffuz'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 24,
    unitNumber: 4.1,
    question: '감기에 유행이다',
    options: [
      'bekor qilmoq',
      'mashq qilmoq',
      'talaffuz',
      'shamollash urfda bo`lmoq'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 25,
    unitNumber: 4.1,
    question: '날씬하다',
    options: ['mashq qilmoq', 'talaffuz', 'shamollash urfda bo`lmoq', 'ozg`in'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 26,
    unitNumber: 4.1,
    question: '배탈',
    options: ['qorin ogrigi', 'toza', 'qorni og`rimoq', 'qo`l telefon'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 4.1,
    question: '깨끗하다',
    options: ['toza', 'qorni og`rimoq', 'qo`l telefon', 'dorixona'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 4.1,
    question: '배탈이 나다',
    options: ['qorni og`rimoq', 'qo`l telefon', 'dorixona', 'dorixonachi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 4.1,
    question: '휴대 전화',
    options: ['qo`l telefon', 'dorixona', 'dorixonachi', 'borgan sari'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 4.1,
    question: '약국',
    options: ['dorixona', 'dorixonachi', 'borgan sari', 'zo`riqmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 31,
    unitNumber: 4.1,
    question: '약사',
    options: ['dorixonachi', 'borgan sari', 'zo`riqmoq', 'kasallik'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 4.1,
    question: '점점',
    options: ['borgan sari', 'zo`riqmoq', 'kasallik', 'bosh ogrigi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 33,
    unitNumber: 4.1,
    question: '무리하다',
    options: ['zo`riqmoq', 'kasallik', 'bosh ogrigi', 'kuchli'],
    correctOptionIndex: 0,
  ),

  // #4.2 Unit

  QuizTest(
    id: 1,
    unitNumber: 4.2,
    question: '우체국 관련 어휘',
    options: [
      'pochtaga oid so`zlar',
      'konvert',
      'yuboruvchi odam',
      'oluvchi odam'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 4.2,
    question: '편지 봉투',
    options: ['konvert', 'yuboruvchi odam', 'oluvchi odam', 'marka'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 4.2,
    question: '보내는 사람',
    options: ['yuboruvchi odam', 'oluvchi odam', 'marka', 'manzil'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 4.2,
    question: '받는 사람',
    options: ['oluvchi odam', 'marka', 'manzil', 'pochta indeksi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 4.2,
    question: '우표',
    options: ['marka', 'manzil', 'pochta indeksi', 'odatiy pochta'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 4.2,
    question: '주소',
    options: ['manzil', 'pochta indeksi', 'odatiy pochta', 'tezkor pochta'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 4.2,
    question: '우편번호',
    options: [
      'pochta indeksi',
      'odatiy pochta',
      'tezkor pochta',
      'ichki pochta'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 4.2,
    question: '보통 우편',
    options: [
      'odatiy pochta',
      'tezkor pochta',
      'ichki pochta',
      'xalqaro tezkor pochta'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 4.2,
    question: '특급 우편',
    options: [
      'tezkor pochta',
      'ichki pochta',
      'xalqaro tezkor pochta',
      'pochta yuki'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 10,
    unitNumber: 4.2,
    question: '국내 우편',
    options: [
      'ichki pochta',
      'xalqaro tezkor pochta',
      'pochta yuki',
      'eltib berish xizmati'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 4.2,
    question: '국제 특급 우편',
    options: [
      'xalqaro tezkor pochta',
      'pochta yuki',
      'eltib berish xizmati',
      'xat'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 4.2,
    question: '소포',
    options: ['pochta yuki', 'eltib berish xizmati', 'xat', 'atkiritka'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 4.2,
    question: '택배',
    options: [
      'eltib berish xizmati',
      'xat',
      'atkiritka',
      'havo orqali yetkazib berish'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 4.2,
    question: '편지',
    options: [
      'xat',
      'atkiritka',
      'havo orqali yetkazib berish',
      'kema orqali yetkazib berish'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 4.2,
    question: '엽서',
    options: [
      'atkiritka',
      'havo orqali yetkazib berish',
      'kema orqali yetkazib berish',
      'fe`l/sifat'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 4.2,
    question: '항공편',
    options: [
      'havo orqali yetkazib berish',
      'kema orqali yetkazib berish',
      'fe`l/sifat',
      'har xil'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 4.2,
    question: '배편',
    options: ['kema orqali yetkazib berish', 'fe`l/sifat', 'har xil', 'tez'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 4.2,
    question: '동사/형용사',
    options: ['fe`l/sifat', 'har xil', 'tez', 'tanlamoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 4.2,
    question: '다르다',
    options: ['har xil', 'tez', 'tanlamoq', 'chaqirmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 20,
    unitNumber: 4.2,
    question: '빠르다',
    options: ['tez', 'tanlamoq', 'chaqirmoq', 'shoshilinch'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 4.2,
    question: '고르다',
    options: ['tanlamoq', 'chaqirmoq', 'shoshilinch', 'sekin-sekin'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 4.2,
    question: '부르다',
    options: ['chaqirmoq', 'shoshilinch', 'sekin-sekin', 'chanqamoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 4.2,
    question: '급하다',
    options: ['shoshilinch', 'sekin-sekin', 'chanqamoq', 'bulutli havo'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 4.2,
    question: '천천히',
    options: ['sekin-sekin', 'chanqamoq', 'bulutli havo', 'smestir'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 4.2,
    question: '목이 마르다',
    options: ['chanqamoq', 'bulutli havo', 'smestir', 'oldindan band qilmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 4.2,
    question: '날씨가 흐리다',
    options: ['bulutli havo', 'smestir', 'oldindan band qilmoq', 'meva'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 4.2,
    question: '학기',
    options: [
      'smestir',
      'oldindan band qilmoq',
      'meva',
      'qo`shimcha(grammatika)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 4.2,
    question: '예약하다',
    options: [
      'oldindan band qilmoq',
      'meva',
      'qo`shimcha(grammatika)',
      'xonadosh'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 4.2,
    question: '과일',
    options: [
      'meva',
      'qo`shimcha(grammatika)',
      'xonadosh',
      'hayotdagi odatlar'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 4.2,
    question: '문법',
    options: [
      'qo`shimcha(grammatika)',
      'xonadosh',
      'hayotdagi odatlar',
      'mukofot olmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 31,
    unitNumber: 4.2,
    question: '룸메이트',
    options: ['xonadosh', 'hayotdagi odatlar', 'mukofot olmoq', 'xarakter'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 4.2,
    question: '생활 습관',
    options: ['hayotdagi odatlar', 'mukofot olmoq', 'xarakter', 'urushmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 33,
    unitNumber: 4.2,
    question: '상을 받다',
    options: ['mukofot olmoq', 'xarakter', 'urushmoq', 'new york'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 4.2,
    question: '성격',
    options: ['xarakter', 'urushmoq', 'new york', 'vazn'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 35,
    unitNumber: 4.2,
    question: '싸우다',
    options: ['urushmoq', 'new york', 'vazn', 'pochtaga oid so`zlar'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 36,
    unitNumber: 4.2,
    question: '뉴욕',
    options: ['new york', 'vazn', 'pochtaga oid so`zlar', 'konvert'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 37,
    unitNumber: 4.2,
    question: '무게',
    options: ['vazn', 'pochtaga oid so`zlar', 'konvert', 'yuboruvchi odam'],
    correctOptionIndex: 0,
  ),

  // #4.3 Unit

  QuizTest(
    id: 1,
    unitNumber: 4.3,
    question: '은행 관련 어휘',
    options: [
      'bankka oid so`zlar',
      'pul qo`ymoq',
      'pul maydalamoq',
      'pul almashtirmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 4.3,
    question: '입금하다=돈을 넣다',
    options: [
      'pul qo`ymoq',
      'pul maydalamoq',
      'pul almashtirmoq',
      'pul yubormoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 4.3,
    question: '출금하다=돈을 찾다',
    options: [
      'pul maydalamoq',
      'pul almashtirmoq',
      'pul yubormoq',
      'kodni o`zgartirmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 4.3,
    question: '환전하다=돈을 바꾸다',
    options: [
      'pul almashtirmoq',
      'pul yubormoq',
      'kodni o`zgartirmoq',
      'imzolamoq/tasdiqlamoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 4.3,
    question: '송금하다=돈을 보내다',
    options: [
      'pul yubormoq',
      'kodni o`zgartirmoq',
      'imzolamoq/tasdiqlamoq',
      'bank carta'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 4.3,
    question: '비밀번호를 누르다=입력하다',
    options: [
      'kodni o`zgartirmoq',
      'imzolamoq/tasdiqlamoq',
      'bank carta',
      'id carta'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 4.3,
    question: '서명하다',
    options: [
      'imzolamoq/tasdiqlamoq',
      'bank carta',
      'id carta',
      'chet elliklar id cartasi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 4.3,
    question: '사인하다',
    options: [
      'imzolamoq/tasdiqlamoq',
      'bank carta',
      'id carta',
      'chet elliklar id cartasi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 4.3,
    question: '통장',
    options: ['bank carta', 'id carta', 'chet elliklar id cartasi', 'muhr'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 10,
    unitNumber: 4.3,
    question: '신분증',
    options: [
      'id carta',
      'chet elliklar id cartasi',
      'muhr',
      'naqd pul cartasi'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 4.3,
    question: '여권',
    options: [
      'chet elliklar id cartasi',
      'muhr',
      'naqd pul cartasi',
      'kridet carta'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 4.3,
    question: '외국인등록증',
    options: [
      'chet elliklar id cartasi',
      'muhr',
      'naqd pul cartasi',
      'kridet carta'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 4.3,
    question: '도장',
    options: ['muhr', 'naqd pul cartasi', 'kridet carta', 'valyuta kursi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 4.3,
    question: '현금카드',
    options: ['naqd pul cartasi', 'kridet carta', 'valyuta kursi', 'buyum'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 4.3,
    question: '신용카드',
    options: ['kridet carta', 'valyuta kursi', 'buyum', 'dollor'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 4.3,
    question: '환율',
    options: ['valyuta kursi', 'buyum', 'dollor', 'ko`tarilmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 4.3,
    question: '물건',
    options: ['buyum', 'dollor', 'ko`tarilmoq', 'siz'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 4.3,
    question: '달러',
    options: ['dollor', 'ko`tarilmoq', 'siz', 'chet el sayohati'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 4.3,
    question: '오르다',
    options: ['ko`tarilmoq', 'siz', 'chet el sayohati', 'apelsin'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 20,
    unitNumber: 4.3,
    question: '당신',
    options: ['siz', 'chet el sayohati', 'apelsin', 'tugatmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 4.3,
    question: '해외여행',
    options: ['chet el sayohati', 'apelsin', 'tugatmoq', 'ariza qo`gozi'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 4.3,
    question: '오렌지',
    options: ['apelsin', 'tugatmoq', 'ariza qo`gozi', 'tushmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 4.3,
    question: '끈내다',
    options: ['tugatmoq', 'ariza qo`gozi', 'tushmoq', 'pul yubormoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 4.3,
    question: '신청서',
    options: ['ariza qo`gozi', 'tushmoq', 'pul yubormoq', 'bankka oid so`zlar'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 4.3,
    question: '내리다',
    options: ['tushmoq', 'pul yubormoq', 'bankka oid so`zlar', 'konvert'],
    correctOptionIndex: 0,
  ),

  // #5.1 Unit

  QuizTest(
    id: 1,
    unitNumber: 5.1,
    question: '기간',
    options: ['muddat', 'soat', 'oy', 'soniya'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 5.1,
    question: '시간',
    options: ['soat', 'oy', 'soniya', 'daqiqа'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 3,
    unitNumber: 5.1,
    question: '달',
    options: ['oy', 'soniya', 'daqiqа', 'kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 4,
    unitNumber: 5.1,
    question: '초',
    options: ['soniya', 'daqiqа', 'kun', 'hafta'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 5,
    unitNumber: 5.1,
    question: '분',
    options: ['daqiqа', 'kun', 'hafta', 'oy'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 6,
    unitNumber: 5.1,
    question: '일',
    options: ['kun', 'hafta', 'oy', 'bir kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 7,
    unitNumber: 5.1,
    question: '주/주일',
    options: ['hafta', 'oy', 'bir kun', 'ikki kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 5.1,
    question: '개월',
    options: ['oy', 'bir kun', 'ikki kun', 'uch kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 9,
    unitNumber: 5.1,
    question: '년',
    options: ['yil', 'uch kun', 'oy', 'bir kun'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 10,
    unitNumber: 5.1,
    question: '하루',
    options: ['bir kun', 'ikki kun', 'uch kun', 'hafta'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 11,
    unitNumber: 5.1,
    question: '이틀',
    options: ['ikki kun', 'uch kun', 'hafta', 'muddat'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 12,
    unitNumber: 5.1,
    question: '사흘',
    options: ['uch kun', 'hafta', 'muddat', 'soat'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 13,
    unitNumber: 5.1,
    question: '경험 관련 어휘',
    options: [
      'tajribaga oid so`zlar',
      'konsert',
      'musiqa festivali',
      'festival'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 14,
    unitNumber: 5.1,
    question: '콘서트',
    options: ['konsert', 'musiqa festivali', 'festival', 'ko`rgazma'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 15,
    unitNumber: 5.1,
    question: '음악회',
    options: ['musiqa festivali', 'festival', 'ko`rgazma', 'teatr'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 16,
    unitNumber: 5.1,
    question: '축제',
    options: ['festival', 'ko`rgazma', 'teatr', 'konsert'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 17,
    unitNumber: 5.1,
    question: '전시회',
    options: ['ko`rgazma', 'teatr', 'konsert', 'mushakbozlik'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 18,
    unitNumber: 5.1,
    question: '연극',
    options: ['teatr', 'konsert', 'mushakbozlik', 'samulluri(milliy o`yin)'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 19,
    unitNumber: 5.1,
    question: '뮤지컬',
    options: [
      'konsert',
      'mushakbozlik',
      'samulluri(milliy o`yin)',
      'rugzakli sayohat'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 20,
    unitNumber: 5.1,
    question: '불꽃놀이',
    options: [
      'mushakbozlik',
      'samulluri(milliy o`yin)',
      'rugzakli sayohat',
      'qo`shimcha ish'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 21,
    unitNumber: 5.1,
    question: '사물놀이',
    options: [
      'samulluri(milliy o`yin)',
      'rugzakli sayohat',
      'qo`shimcha ish',
      'bungee jump(balandlikdan sakrash)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 22,
    unitNumber: 5.1,
    question: '배낭여행',
    options: [
      'rugzakli sayohat',
      'qo`shimcha ish',
      'bungee jump(balandlikdan sakrash)',
      'scuba diving(suv oshtiga sho`ng`ish)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 23,
    unitNumber: 5.1,
    question: '아르바이트',
    options: [
      'qo`shimcha ish',
      'bungee jump(balandlikdan sakrash)',
      'scuba diving(suv oshtiga sho`ng`ish)',
      'stress'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 24,
    unitNumber: 5.1,
    question: '번지점프',
    options: [
      'bungee jump(balandlikdan sakrash)',
      'scuba diving(suv oshtiga sho`ng`ish)',
      'stress',
      'karaoke'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 25,
    unitNumber: 5.1,
    question: '수쿠바다이빙',
    options: [
      'scuba diving(suv oshtiga sho`ng`ish)',
      'stress',
      'karaoke',
      'gmail'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 26,
    unitNumber: 5.1,
    question: '스트레스',
    options: ['stress', 'karaoke', 'gmail', 'hid'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 27,
    unitNumber: 5.1,
    question: '노래방',
    options: ['karaoke', 'gmail', 'hid', 'kalbitang'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 5.1,
    question: '이메일',
    options: ['gmail', 'hid', 'kalbitang', 'roman'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 5.1,
    question: '향수',
    options: ['hid', 'kalbitang', 'roman', 'allaqachon'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 5.1,
    question: '갈비탕',
    options: ['kalbitang', 'roman', 'allaqachon', 'xotirada qolmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 31,
    unitNumber: 5.1,
    question: '소설',
    options: ['roman', 'allaqachon', 'xotirada qolmoq', 'mashhur'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 5.1,
    question: '벌써',
    options: ['allaqachon', 'xotirada qolmoq', 'mashhur', 'madaniy meros'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 33,
    unitNumber: 5.1,
    question: '일본어',
    options: [
      'yapon tili',
      'to`y qilmoq',
      'ishlamoq',
      'sayohatga jo`nab ketmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 5.1,
    question: '결혼을 하다',
    options: [
      'to`y qilmoq',
      'ishlamoq',
      'sayohatga jo`nab ketmoq',
      'kyongju(joy nomi)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 35,
    unitNumber: 5.1,
    question: '일하다',
    options: [
      'ishlamoq',
      'sayohatga jo`nab ketmoq',
      'kyongju(joy nomi)',
      'tarix'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 36,
    unitNumber: 5.1,
    question: '여행을 떠나다',
    options: [
      'sayohatga jo`nab ketmoq',
      'kyongju(joy nomi)',
      'tarix',
      'madaniyat'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 37,
    unitNumber: 5.1,
    question: '경주',
    options: ['kyongju(joy nomi)', 'tarix', 'madaniyat', 'shahar'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 38,
    unitNumber: 5.1,
    question: '역사',
    options: ['tarix', 'madaniyat', 'shahar', 'mashhur'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 39,
    unitNumber: 5.1,
    question: '문화',
    options: ['madaniyat', 'shahar', 'mashhur', 'madaniy meros'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 40,
    unitNumber: 5.1,
    question: '도시',
    options: ['shahar', 'mashhur', 'madaniy meros', 'tomosha qilmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 41,
    unitNumber: 5.1,
    question: '유명하다',
    options: ['mashhur', 'madaniy meros', 'tomosha qilmoq', 'maxsus buyum'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 42,
    unitNumber: 5.1,
    question: '문화재',
    options: [
      'madaniy meros',
      'tomosha qilmoq',
      'maxsus buyum',
      'hwangnam noni'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 43,
    unitNumber: 5.1,
    question: '구경하다',
    options: [
      'tomosha qilmoq',
      'maxsus buyum',
      'hwangnam noni',
      'shuncha vaqt davomida'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 44,
    unitNumber: 5.1,
    question: '특산물',
    options: [
      'maxsus buyum',
      'hwangnam noni',
      'shuncha vaqt davomida',
      'andong(joy nomi)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 45,
    unitNumber: 5.1,
    question: '황남빵',
    options: [
      'hwangnam noni',
      'shuncha vaqt davomida',
      'andong(joy nomi)',
      'chonju(joy nomi)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 46,
    unitNumber: 5.1,
    question: '그동안',
    options: [
      'shuncha vaqt davomida',
      'andong(joy nomi)',
      'chonju(joy nomi)',
      'turli-xil'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 47,
    unitNumber: 5.1,
    question: '안동',
    options: [
      'andong(joy nomi)',
      'chonju(joy nomi)',
      'turli-xil',
      'xotirada qolmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 48,
    unitNumber: 5.1,
    question: '전주',
    options: [
      'chonju(joy nomi)',
      'turli-xil',
      'xotirada qolmoq',
      'umid qilmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 49,
    unitNumber: 5.1,
    question: '다양하다',
    options: [
      'turli-xil',
      'xotirada qolmoq',
      'umid qilmoq',
      'pulgo`ksa ibodatxonasi(joy nomi)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 50,
    unitNumber: 5.1,
    question: '기억에 남다',
    options: [
      'xotirada qolmoq',
      'umid qilmoq',
      'pulgo`ksa ibodatxonasi(joy nomi)',
      'chomsongde(joy nomi)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 51,
    unitNumber: 5.1,
    question: '기대하다',
    options: [
      'umid qilmoq',
      'pulgo`ksa ibodatxonasi(joy nomi)',
      'chomsongde(joy nomi)',
      'anapji(joy nomi)'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 52,
    unitNumber: 5.1,
    question: '불국사',
    options: [
      'pulgo`ksa ibodatxonasi(joy nomi)',
      'chomsongde(joy nomi)',
      'anapji(joy nomi)',
      'tungi manzara'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 53,
    unitNumber: 5.1,
    question: '첨성대',
    options: [
      'chomsongde(joy nomi)',
      'anapji(joy nomi)',
      'tungi manzara',
      'butun umr'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 54,
    unitNumber: 5.1,
    question: '안압지',
    options: ['anapji(joy nomi)', 'tungi manzara', 'butun umr', 'unutmoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 55,
    unitNumber: 5.1,
    question: '야경',
    options: ['tungi manzara', 'butun umr', 'unutmoq', 'manzara'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 56,
    unitNumber: 5.1,
    question: '평생',
    options: ['butun umr', 'unutmoq', 'manzara', 'qobiliyat'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 57,
    unitNumber: 5.1,
    question: '잊다',
    options: ['unutmoq', 'manzara', 'qobiliyat', 'qobiliyati oshmoq/o`smoq'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 58,
    unitNumber: 5.1,
    question: '풍경',
    options: [
      'manzara',
      'qobiliyat',
      'qobiliyati oshmoq/o`smoq',
      'xotirada qolmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 59,
    unitNumber: 5.1,
    question: '실력',
    options: [
      'qobiliyat',
      'qobiliyati oshmoq/o`smoq',
      'xotirada qolmoq',
      'roman'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 60,
    unitNumber: 5.1,
    question: '(실력이)늘다',
    options: [
      'qobiliyati oshmoq/o`smoq',
      'xotirada qolmoq',
      'roman',
      'konsert'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 61,
    unitNumber: 5.1,
    question: '추억',
    options: ['xotirada qolmoq', 'roman', 'konsert', 'muddat'],
    correctOptionIndex: 0,
  ),

  // #5.2 Unit
  QuizTest(
    id: 1,
    unitNumber: 5.2,
    question: '여가 관련 동사',
    options: [
      'bo`sh vaqtga oidga fe`llar',
      'internetda vaqt o`tkazmoq',
      'tozalamoq',
      'uy hayvonlarini boqmoq'
    ],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 2,
    unitNumber: 5.2,
    question: 'SNS를 하다',
    options: [
      'bo`sh vaqtga oidga fe`llar',
      'internetda vaqt o`tkazmoq',
      'tozalamoq',
      'uy hayvonlarini boqmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 3,
    unitNumber: 5.2,
    question: '청소를 하다',
    options: [
      'bo`sh vaqtga oidga fe`llar',
      'internetda vaqt o`tkazmoq',
      'tozalamoq',
      'uy hayvonlarini boqmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 4,
    unitNumber: 5.2,
    question: '애완동물을 기르다',
    options: [
      'bo`sh vaqtga oidga fe`llar',
      'internetda vaqt o`tkazmoq',
      'tozalamoq',
      'uy hayvonlarini boqmoq'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 5,
    unitNumber: 5.2,
    question: '놀이공원에 가다',
    options: [
      'bo`sh vaqtga oidga fe`llar',
      'internetda vaqt o`tkazmoq',
      'parkka bormoq',
      'uy hayvonlarini boqmoq'
    ],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 6,
    unitNumber: 5.2,
    question: '아이쇼핑을 하다',
    options: [
      'bo`sh vaqtga oidga fe`llar',
      'bozor tomosha qilmoq',
      'tozalamoq',
      'uy hayvonlarini boqmoq'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 7,
    unitNumber: 5.2,
    question: '시간 관련 부사',
    options: ['vaqtga oid so`zlar', 'barvaqt', 'kech', 'tez'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 8,
    unitNumber: 5.2,
    question: '일찍',
    options: ['vaqtga oid so`zlar', 'barvaqt', 'kech', 'tez'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 9,
    unitNumber: 5.2,
    question: '늦게',
    options: ['vaqtga oid so`zlar', 'barvaqt', 'kech', 'tez'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 10,
    unitNumber: 5.2,
    question: '빨리',
    options: ['vaqtga oid so`zlar', 'barvaqt', 'kech', 'tez'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 11,
    unitNumber: 5.2,
    question: '천천히',
    options: ['vaqtga oid so`zlar', 'sekin', 'hozir', 'tezda'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 12,
    unitNumber: 5.2,
    question: '아까',
    options: ['vaqtga oid so`zlar', 'biroz oldin', 'hozirgina', 'tezda'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 13,
    unitNumber: 5.2,
    question: '방금',
    options: ['vaqtga oid so`zlar', 'biroz keyin', 'hozirgina', 'tezda'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 14,
    unitNumber: 5.2,
    question: '지금',
    options: ['vaqtga oid so`zlar', 'biroz keyin', 'hozir', 'tezda'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 15,
    unitNumber: 5.2,
    question: '금방',
    options: ['vaqtga oid so`zlar', 'biroz keyin', 'tezda', 'sekkin-sekkin'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 16,
    unitNumber: 5.2,
    question: '이따가',
    options: [
      'vaqtga oid so`zlar',
      'biroz keyin',
      'sekkin-sekkin',
      'hozirgina'
    ],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 17,
    unitNumber: 5.2,
    question: '나중에',
    options: [
      'vaqtga oid so`zlar',
      'biroz keyin',
      'sekkin-sekkin',
      'keyinchalik'
    ],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 18,
    unitNumber: 5.2,
    question: '과거',
    options: ['vaqtga oid so`zlar', 'hozir', 'avval', 'tez'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 19,
    unitNumber: 5.2,
    question: '현재',
    options: ['vaqtga oid so`zlar', 'hozir', 'avval', 'tez'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 20,
    unitNumber: 5.2,
    question: '미래',
    options: ['vaqtga oid so`zlar', 'kelasi/kelajak', 'avval', 'hozir'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 21,
    unitNumber: 5.2,
    question: '심심하다',
    options: ['vaqtga oid so`zlar', 'zerikmoq', 'konsert', 'muddat'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 22,
    unitNumber: 5.2,
    question: '배우',
    options: ['vaqtga oid so`zlar', 'aktyor', 'konsert', 'muddat'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 23,
    unitNumber: 5.2,
    question: '그때',
    options: ['vaqtga oid so`zlar', 'aktyor', 'osha paytda', 'konsert'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 24,
    unitNumber: 5.2,
    question: '콜라',
    options: ['vaqtga oid so`zlar', 'cola', 'aktyor', 'retsep kitob'],
    correctOptionIndex: 1,
  ),
  QuizTest(
    id: 25,
    unitNumber: 5.2,
    question: '팝콘',
    options: ['vaqtga oid so`zlar', 'cola', 'popcorn', 'aktyor'],
    correctOptionIndex: 2,
  ),
  QuizTest(
    id: 26,
    unitNumber: 5.2,
    question: '요리책',
    options: ['vaqtga oid so`zlar', 'cola', 'popcorn', 'retsep kitob'],
    correctOptionIndex: 3,
  ),
  QuizTest(
    id: 27,
    unitNumber: 5.2,
    question: '케이크',
    options: ['tort', 'cola', 'popcorn', 'chili'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 28,
    unitNumber: 5.2,
    question: '이미',
    options: ['allaqachon', 'hozir', 'sekin', 'barvaqt'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 29,
    unitNumber: 5.2,
    question: '잡채',
    options: ['chapche(ovqat nomi)', 'kalbitang', 'tort', 'kolbasa'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 30,
    unitNumber: 5.2,
    question: '회사',
    options: ['korxona', 'uy', 'xona', 'shahar'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 31,
    unitNumber: 5.2,
    question: '천장',
    options: ['tavan', 'poyafzal', 'kapron', 'kafe'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 32,
    unitNumber: 5.2,
    question: '바닥',
    options: ['poyafzal', 'qop', 'stol', 'ko`ylak'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 33,
    unitNumber: 5.2,
    question: '식물',
    options: ['o`simlik', 'bog`', 'toza', 'su`zgich'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 34,
    unitNumber: 5.2,
    question: '연못',
    options: ['ko`l', 'dengiz', 'oyna', 'qanot'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 35,
    unitNumber: 5.2,
    question: '인형',
    options: ['qo`g`irchoq', 'uylama', 'telefon', 'computer'],
    correctOptionIndex: 0,
  ),
  QuizTest(
    id: 36,
    unitNumber: 5.2,
    question: '다양하다',
    options: ['turli-xil', 'katta', 'kichkina', 'o`sha'],
    correctOptionIndex: 0,
  ),

  // #5.3 Unit

  QuizTest(
    id: 1,
    unitNumber: 5.3,
    question: '복잡하다',
    options: [
      'tirband',
      'barvaqt',
      'uchrashuv',
      'yoltirb',
    ],
    correctOptionIndex: 0,
  ),
];
